NHSDigital/dos-integration

Makefile
README.md
build/docker/docker-compose.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-161
Sets up a local database for development and component tests

DI-161 Mock DoS DB for development

---

documentation/adr/001-High-level_design_and_tech_stack.md
documentation/adr/002-Reporting-approach.md

- https://nhsd-jira.digital.nhs.uk/browse/DI-174
This is the ADR for the reporting spike DI-174

DI-174 Investigate and agree reporting approach

---

deployment/serverless.yml
infrastructure/stacks/api-key/secrets.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-200
Strengthen the API Gateway key in order to ensure better security
Removed 'dos-integration' from API endpoint 

DI-200 Update API Key length

---

Makefile
build/automation/var/profile/task.mk
infrastructure/stacks/splunk-logs/data.tf
infrastructure/stacks/splunk-logs/locals.tf
infrastructure/stacks/splunk-logs/main.tf
infrastructure/stacks/splunk-logs/providers.tf
infrastructure/stacks/splunk-logs/terraform.tf
infrastructure/stacks/splunk-logs/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-158
This ticket is to add infrastructure as code for lambda logs to be pushed to Splunk

DI-158 Set up Splunk logging infrastructure

---

application/event_processor/change_request.py
application/event_processor/tests/test_event_processor.py
application/event_sender/requests.http
test/component/features/resources/valid_change_request.json
test/component/features/steps/event_processor_steps.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-148
This ticket is to modify the public name field in the change request from `publicname` to `public_name` as the latter is expected by DoS CR.

DI-148 Amend the DoS API Gateway to allow update of Public Name

---

Makefile
application/.gitignore
build/automation/lib/docker.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/pipeline-component-test.mk
build/automation/var/profile/task.mk
build/automation/var/project.mk
build/docker/docker-compose.yml
build/docker/event-processor/Dockerfile
build/docker/serverless/Dockerfile
deployment/serverless.yml
infrastructure/modules/s3/main.tf
infrastructure/modules/s3/outputs.tf
infrastructure/modules/s3/variables.tf
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/codebuild.tf
infrastructure/stacks/development-pipeline/codepipeline.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/policies.tf
infrastructure/stacks/development-pipeline/providers.tf
infrastructure/stacks/development-pipeline/terraform.tf
infrastructure/stacks/development-pipeline/unit-tests-buildspec.yml
infrastructure/stacks/development-pipeline/variables.tf
test/.gitignore
test/component/features/utilities/utilities.py

- Create Development Pipeline for the Master Branch
Terraform scripts and updates to MakeFiles to provision CodePipeline for Continuous integration and deployment to Dev environment. 
Build has the Following steps
- Trigger from change to Master 
- Run unit tests and publish test report
- Build components
- Run Component tests and publish test report
- Publish components
- Deploy
- add `docker-hub-signin` make target to avoid rate limiting errors from docker hub for repeated pullls of nhsd/tools
- add junit output to both unit and component tests and integrate with code build so test results visible in AWS console
- new ct.mk file for running component tests on linux build agent
- downgrade docker compose to 3.8 as 3.9 was not supported on the build agent 
- remove the dependson from …

DI-176 Dev pipeline definition

---

infrastructure/stacks/development-pipeline/codebuild.tf

-https://nhsd-jira.digital.nhs.uk/browse/DI-176
Small issue with variable case 

DI-176 Dev pipeline simplified

---

application/common/middlewares.py
application/common/utilities.py
application/event_processor/event_processor.py
application/event_receiver/event_receiver.py
application/event_sender/change_request.py
application/event_sender/change_request_logger.py
application/event_sender/event_sender.py
application/event_sender/tests/test_change_request.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-223
Added some additional middelwares, one for setting request-id as correlation-id if none provided in header and one for ensuring we get a JSON log for any unhandled exceptions

DI-222 Json logging some extra bits

---

application/event_processor/event_processor.py
application/event_processor/reporting.py
application/event_processor/tests/test_event_processor.py
application/event_processor/tests/test_reporting.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-98
Log unmatched pharmacy services that have come through into DI from nhs.uk in order to compile an ad hoc list for reporting 
- Added separate function to log  unmatched  pharmacies
- Added unit tests 

DI-98 Log details of unmatched pharmacies into splunk

---

application/event_processor/changes.py
application/event_processor/dos.py
application/event_processor/nhs.py
application/event_processor/tests/conftest.py
application/event_processor/tests/test_changes.py
application/event_processor/tests/test_dos.py
application/event_processor/tests/test_event_processor.py

https://nhsd-jira.digital.nhs.uk/browse/DI-178
- Added functionality for DoS postcode validation
- Added DoSLocation object with functionality to retrieve from DoS DB and cache results.
- Change requests check if postcode is valid and do not add postcode field to change if it is not according to requirements on ticket.

DI-178 Added postcode dos location validation

---

build/automation/var/profile/dev.mk
build/automation/var/profile/task.mk

- https://nhsd-jira.digital.nhs.uk/browse/DI-253
Change non-prod DoS read replica database to the new version 12 one. DoS plan to retire the the old one imminently 
- Check the deployment is using the version 12 version of the read replica database

DI-253 Change dos read replica database for texas non-prod

---

Makefile
application/common/tests/test_utilities.py
application/common/utilities.py
application/event_processor/change_event_validation.py
application/event_processor/event_processor.py
application/event_processor/tests/test_event_processor.py
application/fifo_dlq_handler/fifo_dlq_handler.py
application/fifo_dlq_handler/requirements.txt
application/fifo_dlq_handler/tests/test_fifo_dlq_handler.py
build/automation/var/profile/task.mk
build/docker/fifo-dlq-handler/.gitignore
build/docker/fifo-dlq-handler/Dockerfile
build/docker/fifo-dlq-handler/VERSION
deployment/serverless.yml
infrastructure/stacks/api-gateway-sqs/data.tf
infrastructure/stacks/api-gateway-sqs/sqs.tf
infrastructure/stacks/api-gateway-sqs/variables.tf
infrastructure/stacks/lambda-iam-roles/main.tf
infrastructure/stacks/lambda-iam-roles/variables.tf
infrastructure/stacks/splunk-logs/main.tf
infrastructure/stacks/splunk-logs/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-242
This ticket is to add a dead letter queue from the FIFO queue.
- New lambda called fifo-dlq-handler (First In First Out Dead Letter Queue Handler)
- Change event not retried if failed in event-processor

DI-242 Create DLQ for failed FIFO change event to DynamoDB

---

application/common/dynamodb.py
application/common/utilities.py
application/event_processor/dos.py
application/event_processor/event_processor.py
application/event_processor/tests/test_dos.py
application/event_processor/tests/test_event_processor.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-266
- https://nhsd-jira.digital.nhs.uk/browse/DI-268
These changes ensure protection from SQL-injection attacks from user inputted values and explicitly closes the DoS DB connection at the end of each Lambda execution.
- Sanitise user input values in SQL queries
- Close DB in finally block
- Some shuffling of event processor main line order

DI-266 Dos database management

---

infrastructure/stacks/development-pipeline/policies.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-274
Update policy permissions to enable deployment 
-  add dynamodb:CreateTable and update permissions relating to lambda event source mappings

DI-274 Fix broken pipeline

---

infrastructure/stacks/development-pipeline/policies.tf

-https://nhsd-jira.digital.nhs.uk/browse/DI-277
Another permission missing from the pipeline

Add yet another missing permission

---

infrastructure/stacks/lambda-iam-roles/main.tf

Remove extraneous comma

---

application/common/dynamodb.py
application/common/tests/test_dynamodb.py
application/event_processor/event_processor.py
application/fifo_dlq_handler/fifo_dlq_handler.py
application/fifo_dlq_handler/tests/test_fifo_dlq_handler.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-279
Updated DynamoDb TTL and EventReceived Attributes to Numeric (not string)
This change will fix the sorting issue 
- Bugfix (non-breaking change which fixes an issue)

DI-279 Update TTL And Event Received Time To Numeric

---

infrastructure/stacks/development-pipeline/build-buildspec.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-283
Comment out component tests as we no longer have any as they are being replaced by e2e tests shortly, this will enable the build to pass again 

DI-283 Comment out component tests

---

infrastructure/stacks/development-pipeline/build-buildspec.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-283
Need to comment out the reports as not tests now running 

DI-283 Remove component tests

---

build/automation/var/profile/dev.mk

- https://nhsd-jira.digital.nhs.uk/browse/DI-285
dev.mk was not updated with DI-240

DI-285 Update dev.mk inline with DI-240 changes

---

Makefile
application/event_processor/dos.py
application/event_processor/event_processor.py
application/event_processor/tests/test_dos.py
application/event_processor/tests/test_event_processor.py
deployment/serverless.yml

-https://nhsd-jira.digital.nhs.uk/browse/DI-280
This ticket is to get the database password from a secret manager instead of getting it from the environment variable.
- 

DI-280 Get Database Password From SecretManager

---

Makefile
application/event_sender/event_sender.py
application/event_sender/tests/test_event_sender.py
build/automation/var/profile/test.mk

DI-289 Create test environment and fix issue with status code

---

infrastructure/stacks/development-pipeline/notify.tf
infrastructure/stacks/development-pipeline/policies.tf
infrastructure/stacks/development-pipeline/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-287
Add some bits to add build notifications to slack 
- Add some bits to add build notifications to slack 
- Add missing permission

DI-287 Fix policy and add build notifications

---

application/event_sender/event_sender.py
application/event_sender/tests/test_event_sender.py
build/automation/var/profile/perf.mk

- https://nhsd-jira.digital.nhs.uk/browse/DI-291

DI-291 Fix typo and add performance test make file

---

infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/codebuild.tf
infrastructure/stacks/development-pipeline/codepipeline.tf
infrastructure/stacks/development-pipeline/deploy-buildspec.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-289
Add deploy to test into pipeline

DI-289 Add deploy of test environment

---

Makefile

- https://nhsd-jira.digital.nhs.uk/browse/DI-291
Little add on to make sure the mock gets deployed in the performance test environment 

Adding a mock into the performance test environment

---

application/event_processor/event_processor.py
application/event_processor/requirements.txt
application/event_processor/tests/test_event_processor.py
application/event_sender/event_sender.py
application/event_sender/tests/test_event_sender.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-257
Add additional metric, renamed the original one and remove the default dimensions

DI-257 Add additional metric, rename and remove default dimensions

---

build/docker/serverless/Dockerfile

This is to fix a serverless version error in the codepipeline. Once approved this change will be applied to the pipeline.

Fix serverless version error

---

infrastructure/stacks/development-pipeline/policies.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-297
Forgot to add kms permissions to the pipeline policy

Add kms permissions to the pipeline

---

Makefile
application/common/dynamodb.py
application/dos_api_gateway/dos_api_gateway.py
application/dos_api_gateway/tests/test_dos_api_gateway.py
application/eventbridge_dlq_handler/eventbridge_dlq_handler.py
application/eventbridge_dlq_handler/requirements.txt
application/eventbridge_dlq_handler/tests/test_eventbridge_dlq_handler.py
build/automation/var/profile/dev.mk
build/automation/var/profile/task.mk
build/docker/eventbridge-dlq-handler/.gitignore
build/docker/eventbridge-dlq-handler/Dockerfile
build/docker/eventbridge-dlq-handler/VERSION
deployment/serverless.yml
infrastructure/stacks/dos-api-gateway-mock/main.tf
infrastructure/stacks/eventbridge/data.tf
infrastructure/stacks/eventbridge/main.tf
infrastructure/stacks/eventbridge/variables.tf
infrastructure/stacks/lambda-iam-roles/main.tf
infrastructure/stacks/lambda-iam-roles/variables.tf
infrastructure/stacks/splunk-logs/main.tf
infrastructure/stacks/splunk-logs/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-243

DI-243 Dlq for undelivered change requests

---

build/automation/etc/githooks/scripts/python-code-pre-commit.sh
infrastructure/stacks/development-pipeline/policies.tf
test/integration/features/e2e_di_test.feature
test/integration/features/steps/parent_steps.py
test/integration/features/utilities/utils.py

More policy updates to allow build to pass

---

Makefile
build/automation/var/profile/dev.mk
infrastructure/stacks/development-pipeline/codebuild.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/integration-tests-buildspec.yml
infrastructure/stacks/development-pipeline/policies.tf
infrastructure/stacks/development-pipeline/variables.tf
test/integration/features/parent_features.feature
test/integration/features/steps/parent_steps.py
test/integration/features/utilities/utils.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-292
Small updates to permissions descriptions and timeouts to allow integration tests to run in the pipeline

DI-292 Up the timeout

---

test/integration/features/parent_features.feature
test/integration/features/steps/parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-302
-
Modified the LAT Long test scenario's step definition query parameters to ensure the pipeline builds do not fail as a result.
Test Step defs and Feature file modifications.

DI-302 Fix invalid postcode lat long test

---

build/automation/var/profile/dev.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/task.mk
build/automation/var/profile/test.mk
infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/providers.tf
infrastructure/stacks/cloudwatch-dashboard/terraform.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-144
New terraform stack to build cloudwatch dashboard

DI-144 Add terraform script for cloudwatch dashboard

---

Makefile

Add dashboard stack to Makefile

---

application/event_processor/changes.py

Fix log message for opening times invalidation

---

test/integration/features/parent_features.feature
test/integration/features/steps/parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-303
-
Fix log exception bug for Opening Times Test
Opening Times test scenarios

DI-303 Add opening times exception step def

---

Makefile

DI-144 Add dashboard to deploy

---

infrastructure/stacks/development-pipeline/policies.tf

Dashboard policy for deployment

---

build/automation/var/profile/dev.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/task.mk
build/automation/var/profile/test.mk
deployment/serverless.yml
infrastructure/stacks/api-gateway-sqs/api-gateway-responses.tf
infrastructure/stacks/api-gateway-sqs/api-gateway.tf
infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf
infrastructure/stacks/splunk-logs/main.tf
infrastructure/stacks/splunk-logs/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-306
Fix bug when messages from NHS UK had special characters including ampersands in fields

DI-306 Fix bug and improve related logging and monitoring

---

deployment/serverless.yml

Undo the service change as the build failed

---

application/eventbridge_dlq_handler/eventbridge_dlq_handler.py
application/eventbridge_dlq_handler/tests/test_eventbridge_dlq_handler.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-301
This PR will improve the logging on the eventbridge dlq handler so it report message attributes including the error message and error message http status code. 
- Check this link to cloud watch to check what is now being logged https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fuec-dos-int-di-301-eventbridge-dlq-handler/log-events/2022$252F02$252F02$252F$255B$2524LATEST$255Dbb571baa252640258e1080cd8c6a4cfe

DI-301 Improve eventbridge dlq handler logging

---

infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-256
Monitoring the number of Changed Events that are coming through from NHS.UK and the number of Change requests that have been successfully delivered into DoS.

DI-256 Add change event and change request metric to dashboard

---

application/eventbridge_dlq_handler/eventbridge_dlq_handler.py
application/eventbridge_dlq_handler/tests/test_eventbridge_dlq_handler.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-308
Fix for error message in Eventbridge DLQ Handler logs 

DI-308 Fix error message for eventbridge dlq handler logs

---

Makefile
test/integration/features/parent_features.feature
test/integration/features/steps/parent_steps.py
test/integration/features/utilities/log_stream.py
test/integration/features/utilities/utils.py

[JIRA Ticket](https://nhsd-jira.digital.nhs.uk/browse/DI-243)
Added integration tests for the new DLQ.
This involved pulling a new env var into the e2e-test.
Moving around the correlation-id customization code into a new function in utils.py
Adding some new step functions to enable setting correlation id
Adding a check in the process payload step to add a generated correlation id if one is not manually set.
Changes to the payload sender with correlation id field now mandatory.

DI-243 Create DLQ Integration test scenarios

---

Makefile
infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-309
Add event bridge metrics to the dashboard and resize rearrange and retitle a few bits

Add Eventbridge stuff to Dashboard and move stuff around a bit

---

infrastructure/stacks/cloudwatch-dashboard/main.tf

- [DI-309](https://nhsd-jira.digital.nhs.uk/browse/DI-309)
Update metric resolution to 1  min instead of 5

Update metrics to 1 min resolution

---

test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

Reduce the correlation id length to stop it erroring in the DoS API Gateway

Reduce correlation id length

---

infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-304
Add saved queries for quick log inspection

DI-304 Add saved log insight queries

---

infrastructure/stacks/development-pipeline/policies.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-304
Add missing permissions to the pipeline to allow these to be deployed

DI-304 Add missing permissions

---

Makefile
build/automation/var/profile/perf.mk

Performance test using actual dos gateway and upping users and run time

---

deployment/serverless.yml

Add stackTags to enable tighter permissions

---

test/integration/features/parent_features.feature
test/integration/steps/test_parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-312
-
Automate the Tests for [DI-311](https://nhsd-jira.digital.nhs.uk/browse/DI-311) - Log Opening Times issue - to verify that all expected attributes for the Invalid Opening Times report are identified in the logs to be pulled by Splunk
Added a new step to the step definition file in test suite.

DI-312 Add opening times exception report test

---

application/common/tests/conftest.py
application/common/tests/test_utilities.py
application/common/utilities.py
application/event_processor/changes.py
application/event_processor/reporting.py
application/event_processor/tests/test_event_processor.py
application/event_processor/tests/test_reporting.py
application/eventbridge_dlq_handler/eventbridge_dlq_handler.py
application/eventbridge_dlq_handler/tests/test_eventbridge_dlq_handler.py
application/fifo_dlq_handler/fifo_dlq_handler.py
application/fifo_dlq_handler/tests/test_fifo_dlq_handler.py
infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/cloudwatch-dashboard/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-258
Track how many Changed Events and Change Requests are being directed into the 2 DLQs within the DI Pathway in order to see at a glance whether there are any potential bottlenecks and/or connectivity failures.
- Added new DLQ Failures graph to the cloud watch dashboard

DI-258 Monitor DLQ Failures

---

README.md

- https://nhsd-jira.digital.nhs.uk/browse/DI-202

DI-202 Update readme with details about the correlation id

---

Makefile
build/automation/var/profile/dev.mk
build/automation/var/profile/task.mk
build/automation/var/profile/test.mk
infrastructure/stacks/development-pipeline/integration-tests-buildspec.yml
test/integration/features/parent_features.feature
test/integration/resources/payloads/aligned_payload.json
test/integration/resources/payloads/no_changes_payload.json
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/changed_events.py
test/integration/steps/utilities/utils.py

https://nhsd-jira.digital.nhs.uk/browse/DI-315
-
The mechanism for [DI-235](https://nhsd-jira.digital.nhs.uk/browse/DI-235) requires whoever's on call to manually invoke the event-replay Lambda to trigeer this processs. This test will simulate this process to re-apply a Changed Event
- Included additional test to cover scenario with no CR for an aligned CE load injection.

DI-315 Add change event reprocess function and steps

---

application/event_processor/nhs.py
application/event_processor/opening_times.py
application/event_processor/tests/STANDARD_EVENT.json
application/event_processor/tests/test_changes.py
application/event_processor/tests/test_event_processor.py
application/event_processor/tests/test_nhs.py
application/event_processor/tests/test_opening_times.py
application/event_processor/tests/test_reporting.py
test/demo/demo_events/demo_event5_openingtimes_changes.json
test/integration/resources/payloads/aligned_payload.json
test/integration/resources/payloads/closed_day_payload.json
test/integration/resources/payloads/expected_schema.json
test/integration/resources/payloads/multi_services_payload.json
test/integration/resources/payloads/no_changes_payload.json
test/integration/resources/payloads/opening_days_changes.json
test/integration/resources/payloads/opening_times_changes.json
test/performance/create_change_events/resources/change_events.json

- https://nhsd-jira.digital.nhs.uk/browse/DI-320
Payload needs to work with OpeningTime and ClosingTime fields rather than a single Times field.
- Logic and all unit tests

DI-320 Changing Times field to OpeningTime and ClosingTime

---

application/event_processor/changes.py
application/event_processor/event_processor.py
application/event_processor/tests/test_event_processor.py
application/event_sender/change_request_logger.py
application/event_sender/tests/test_change_request_logger.py
build/automation/var/profile/dev.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/test.mk

Add some additional logging to understand what is going on 

Add sequence numbers etc

---

test/integration/features/parent_features.feature
test/integration/steps/test_parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-321
-
Fix test suite bug caused after schema update got applied.
- Update step def files
- Update Scenario naming structure

DI-321 Update test suite after schema fix

---

application/event_processor/dos.py
application/event_processor/tests/test_dos.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-316
Investigating and fixing  the overlapping time issues seen in performance tests

DI-316 Specified opening times SQL query issue

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/events.py

https://nhsd-jira.digital.nhs.uk/browse/DI-323
-
Specified and Standard opeining-times data validations - Includes testing different variations of the Specified and Standard opening-times data set.

DI-323 Improve test coverage scenarios

---

application/common/opening_times.py
application/common/tests/test_opening_times.py
application/event_processor/nhs.py
application/event_processor/tests/test_changes.py
application/event_processor/tests/test_nhs.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-324

DI-324 Fixing specified closed times bug

---

application/event_processor/nhs.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-325

DI-325 Fixing edge case from 324

---

build/automation/var/project.mk

DI-XXX Whats going on

---

deployment/serverless.yml

Add missing serverless variable

---

test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

[-](https://nhsd-jira.digital.nhs.uk/browse/DI-327)
There has been a new process_payload added to enable custom sequence id's
There has also been a few new steps added to utilise this new feature
The new tests have been added to feature 4. They all revolve around the sequence-id.
Changes to the utils.py file
- Integration Test

DI-323 New sequence id tests added

---

application/event_processor/change_request.py
application/event_processor/changes.py
application/event_processor/tests/test_changes.py
application/event_processor/tests/test_event_processor.py
test/integration/steps/utilities/events.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-330
Currently, we use an incorrect address format for change requests
"address": [                
"3 Gloucester Road",                
"Bristol"            
],        
"postcode": "BS1 4SB", 
**Changed to:**
"address": {
"address_lines": [
"2 Gloucester Road",
"Bristol"            
],            
"post_code": "BS1 4SB"
}  

DI-330 Fix address and postcode change request format issue

---

infrastructure/stacks/api-gateway-sqs/data.tf
infrastructure/stacks/api-gateway-sqs/iam.tf
infrastructure/stacks/api-gateway-sqs/sqs.tf
infrastructure/stacks/api-gateway-sqs/variables.tf
infrastructure/stacks/dynamo-db/data.tf
infrastructure/stacks/dynamo-db/main.tf
infrastructure/stacks/dynamo-db/variables.tf
infrastructure/stacks/lambda-iam-roles/main.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-288
- https://nhsd-jira.digital.nhs.uk/browse/DI-328

DI-328 Kms for ddb and sqs

---

application/event_processor/changes.py
infrastructure/stacks/cloudwatch-dashboard/main.tf
infrastructure/stacks/dynamo-db/main.tf

Few tweaks to the Dashboard and terrraform fmt

---

application/event_processor/changes.py
application/event_processor/event_processor.py
infrastructure/stacks/cloudwatch-dashboard/main.tf

Few dashboard and saved log queries tweaks

---

application/common/dos.py
application/common/opening_times.py
application/common/tests/test_dos.py
application/common/tests/test_opening_times.py
application/event_sender/tests/__init__.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-343

DI-343 Fixed Spec Open list EQ and db retrieval edge case

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

https://nhsd-jira.digital.nhs.uk/browse/DI-342
Improve test suite with functionalities to verify individual changes sent to Dos. These changes include contacts(phone numbers and websites) and address changes.

DI-342 Add Dos change verification tests

---

Makefile

Always deploy api key

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/steps/pytest.ini
test/integration/steps/test_parent_steps.py

[-](https://nhsd-jira.digital.nhs.uk/browse/DI-344)
This adds a series of integration tests that NHSUK have that we didn't have coverage for.
- None of note
- Integration tests

DI-344 Add new tests from NHSUK suite

---

build/automation/var/profile/demo.mk
build/automation/var/profile/live.mk

Prod make files

---

application/event_processor/change_request.py
application/event_processor/tests/test_change_request.py

DI-331 Add new replace_opening_dates_mode to dos change requests

---

Makefile
infrastructure/stacks/development-pipeline/data.tf

Seperate build and deployment of authorizer

---

Makefile
build/automation/etc/githooks/scripts/remove-local-git-tags-pre-commit.sh
infrastructure/stacks/development-pipeline/build-buildspec.yml

DI-XXX Tweak make target so version set by caller

---

build/automation/lib/docker.mk

Add trace logging

---

application/event_sender/event_sender.py

Log explicit if health check fail

---

application/common/tests/test_aws.py
application/common/tests/test_middlewares.py
application/event_processor/tests/test_event_processor.py
application/event_sender/change_request.py
application/event_sender/event_sender.py
application/event_sender/tests/test_change_request.py
application/event_sender/tests/test_event_sender.py

Dont retry if no changes to make

---

application/common/middlewares.py

DI-348 Added msg into validation err str

---

test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/log_stream.py

Increase timeout for tests

---

test/integration/steps/test_parent_steps.py

Slow tests down to wait for DoS CronJob

---

build/automation/var/profile/demo.mk
build/automation/var/profile/live.mk
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/deployment-pipelines/live_codebuild.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-184
This change is to add the live codebuild section of the deployment pipelines terraform stack.  Documentation for this ticket will be in another PR.

DI-184 Set up/Enable live deployments in deployment pipeline

---

application/event_sender/event_sender.py
build/automation/var/profile/demo.mk

Change demo change-request location and dos api health check fixes

---

test/integration/features/F004_Error_Handling.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/aws.py
test/integration/steps/utilities/get_secrets.py
test/integration/steps/utilities/utils.py

https://nhsd-jira.digital.nhs.uk/browse/DI-360
-
Improve test suite with functionalities to improve resilience and correct flakey outputs.
AC:
Additional test scenarios will be tagged to run on Test env
All new and existing regression scenarios will pass execution
- Fix "get_service_id" function error causing F006S008 opening-times failed tests.
- Add scenario to Verify that Standard day can be set back to Open after initially set to Close.
- Add scenario to Verify that Specified date can be set back to Open after initially set to Close.

DI-360 Refactor improve resilience v3

---

Makefile
build/automation/lib/serverless.mk
build/automation/var/project.mk
build/docker/serverless/Dockerfile
deployment/serverless.yml
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build_image_codebuild.tf
infrastructure/stacks/development-pipeline/codebuild.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/deploy-buildspec.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-363
This PR is to change our serverless deployments to use a pulled down image from ECR.

DI-363 Build serverless image with plugins separately from deployments

---

Makefile
README.md
infrastructure/stacks/development-pipeline/codepipeline.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-task-environment-from-tag-buildspec.yml
infrastructure/stacks/development-pipeline/delete_task_environment_from_tag.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-370
This PR adds a codebuild project to remove a task environment based on the tag

DI-370 Destroy a task environment on commit tag

---

Makefile
build/docker/serverless/Dockerfile
deployment/serverless.yml
infrastructure/stacks/cloudwatch-dashboard/alerts.tf
infrastructure/stacks/cloudwatch-dashboard/data.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/lambda-security-group/alerts.tf
infrastructure/stacks/lambda-security-group/variables.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-368
This changes the serverless version to V3, once a new docker image has been built with the correct version then an upgrade should work smoothly. 

DI-368 Upgrade Serverless to V3

---

application/common/tests/conftest.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-379

DI-379 Fix dynamodb unit test

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

https://nhsd-jira.digital.nhs.uk/browse/DI-372
-
To reduce the amount of time it takes to validate certain exceptions in order to make the end to end test more efficient and less time consuming
- Identify the validations that are NOT exceptions that can be improved
- Amend the tests for these validations to check the DoS db
- Maintain all exception validations through logs

DI-372 Remove validation checks via logs

---

test/integration/steps/test_parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-382
Fix Scenario Outline syntax error causing tests to fail on the pipeline.

Modify step def syntax for scenario outline

---

infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-249 Simple Merge test to trigger delete env

---

infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-249 Merge another simple change to trigger codebuild stage

---

deployment/serverless.yml
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-242 Another simple merge trigger

---

deployment/serverless.yml
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/unit-tests-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-242 Another simple merge test

---

README.md
deployment/serverless.yml
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/unit-tests-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-242 A simple merge test

---

README.md
deployment/serverless.yml
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/unit-tests-buildspec.yml
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

DI-242 simple merge test

---

Makefile
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-task-environment-on-pr-merged-buildspec.yml
infrastructure/stacks/development-pipeline/delete_task_environment_on_pr_merged.tf

DI-366 delete env on pr merge

---

infrastructure/stacks/deployment-pipelines/demo_codebuild.tf
infrastructure/stacks/deployment-pipelines/deploy-buildspec.yml
infrastructure/stacks/deployment-pipelines/live_codebuild.tf

This is the currently deployed version of the deployment codebuild stages

Increase deployment timeout and fix serverless command error

---

test/integration/features/F002_Invalid_Change_Events.feature
test/integration/steps/test_parent_steps.py

JIRA https://nhsd-jira.digital.nhs.uk/browse/DI-378
Added a new integration test to verify the functionality of the unmatched_service_type log
Only really minor additions
- Test

DI-378 Unmatched Service Type Integration Test

---

application/event_processor/reporting.py
application/event_processor/tests/test_reporting.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-339

DI-339 Adding an extra reporting column

---

Makefile
README.md
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-task-environment-on-pr-merged-buildspec.yml
infrastructure/stacks/development-pipeline/delete_task_environment_on_pr_merged.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-366
This ticket deletes an environment when a PR is merged.

DI-366 Codebuild job to destroy an environment on PR being merged

---

Makefile
README.md
build/automation/lib/slack/codebuild-pipeline-failure.json
build/automation/lib/slack/codebuild-pipeline-success.json
infrastructure/stacks/after-lambda-deployment/splunk.tf
infrastructure/stacks/development-pipeline/build-environment-buildspec.yml
infrastructure/stacks/development-pipeline/build_environment.tf
infrastructure/stacks/development-pipeline/build_image_codebuild.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-task-environment-on-pr-merged-buildspec.yml
infrastructure/stacks/development-pipeline/delete_task_environment_from_tag.tf
infrastructure/stacks/development-pipeline/delete_task_environment_on_pr_merged.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-367
This PR is to add the ability to automatically deploy all task branches on every push. 
- A new deployment will take roughly 15/20 mins
- A repeat deployment will take 5/10 mins
- It will only deploy if the branch name is task/DI-Number so task/DI-XXX will not deploy

DI-367 Deploy environment on branch push

---

application/common/service_type.py
application/event_processor/changes.py
application/event_processor/event_processor.py
application/event_processor/reporting.py
application/event_processor/tests/test_event_processor.py
application/event_processor/tests/test_reporting.py

https://nhsd-jira.digital.nhs.uk/browse/DI-386
https://nhsd-jira.digital.nhs.uk/browse/DI-381
https://nhsd-jira.digital.nhs.uk/browse/DI-385
https://nhsd-jira.digital.nhs.uk/browse/DI-387

DI-356 All dentist report updates

---

application/common/dos.py
application/common/tests/conftest.py
application/common/tests/test_dos.py
application/event_processor/tests/conftest.py
application/event_processor/tests/test_changes.py
application/event_processor/tests/test_event_processor.py
application/event_processor/tests/test_reporting.py

-https://nhsd-jira.digital.nhs.uk/browse/DI-404
DoSService object fields are kept in object rather than string list. Fixed the resulting test errors. Removed duplicate testing functions.

DI-404 Small DOSService refractor

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/steps/test_parent_steps.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-402
Added tests for the new dentist Splunk reports. They're largely the same as existing tests for similar.
Nothing major has been changed just additional steps and features.
Integration Test

DI-402 Splunk tests for dentists

---

test/integration/features/F004_Error_Handling.feature

https://nhsd-jira.digital.nhs.uk/browse/DI-412
-
Fix sequence id test error.
Acceptance Criteria:
All tests with @pharmacy_cloudwatch_queries tag passes.
Introduced appropriate speech marks on test step.

DI-412 Fix alphanumeric seq id test on release 1.0.0

---

test/integration/features/F004_Error_Handling.feature

https://nhsd-jira.digital.nhs.uk/browse/DI-414
-
Add previously skipped Sequence number less than previous raises exception test.

DI-414 Add sequence id test

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/test_parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-415
-
Tests will input different variations of empty website and phone Changed event data to assert no Change requests are created.

DI-415 Tests to validate no cr for empty contact data

---

test/integration/features/F001_Valid_Change_Events.feature

https://nhsd-jira.digital.nhs.uk/browse/DI-416
-

DI-416 Correct var syntax

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/test_parent_steps.py

https://nhsd-jira.digital.nhs.uk/browse/DI-417
-

DI-417 Remove scenario outline empty quotes

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_parent_steps.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-410
A new generic given step and further streamlining of the test_parent_steps file to try and create as few required steps as possible.
Test run evidence in the DI-410 ticket.
- Primarily the given changes are what's new. 
- Some amendments have been made to Then steps also where possible.
- Test

DI-410 Generify given for properties

---

application/test_db_checker_handler/test_db_checker_handler.py
application/test_db_checker_handler/tests/test_test_db_checker_handler.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

https://nhsd-jira.digital.nhs.uk/browse/DI-430
Automate the selection of odscodes into test scenarios via SQL queries thereby minimising the chance of failed tests occuring from pharmacies with already altered data being reused in another test of the same scenario.
- DB Checker handler Lambda returns odscodes with specified contacts data
Sql querry added to db checker handler

DI-430 Automate odscode selection with contact

---

infrastructure/stacks/development-pipeline/build-image-buildspec.yml
infrastructure/stacks/development-pipeline/delete_release_environment_on_pr_merged.tf
infrastructure/stacks/development-pipeline/delete_task_environment_from_tag.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-443
These fixes are to make the codebuild stages work as intended.

DI-443 Fix Delete Task Environments Codebuild Stage

---

.github/dependabot.yml

- https://nhsd-jira.digital.nhs.uk/browse/DI-446
This PR is to set up dependabot to see how it works. If any improvements are needed it will be in a follow up PR.

DI-446 Set up GitHub Dependabot

---

.gitignore
Makefile
application/common/tests/conftest.py

- https://nhsd-jira.digital.nhs.uk/browse/DI-451

DI-451 Fix coverage in Sonarcloud

---

.gitignore
Makefile
build/automation/var/profile/tools.mk
infrastructure/modules/s3/main.tf
infrastructure/stacks/development-pipeline/build_release.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/development_pipeline_codebuild.tf
infrastructure/stacks/development-pipeline/development_pipeline_codepipeline.tf
infrastructure/stacks/development-pipeline/locals.tf
infrastructure/stacks/development-pipeline/security_groups.tf
infrastructure/stacks/development-pipeline/setup-integration-tests-buildspec.yml
infrastructure/stacks/development-pipeline/variables.tf
infrastructure/stacks/release-pipeline/codepipeline.tf

- https://nhsd-jira.digital.nhs.uk/browse/DI-374
This PR is to trigger a Jenkins job to run to deploy the DoS Environment (regressiondi).
- Added an additional stage to the development pipeline to run this Jenkins Job
- This new codebuild project is attached to the mgmt VPC

DI-374 Triggering a Jenkins deploy from AWS Codebuild

---

.github/dependabot.yml
.github/workflows/code-quality.yml
.github/workflows/code-security.yml
.github/workflows/dependency-review.yml
Makefile
build/automation/lib/docker.mk
build/docker/serverless/Dockerfile
infrastructure/.gitignore

- https://nhsd-jira.digital.nhs.uk/browse/DI-447
This PR sets up security scanning for Dockerfiles, Serverless Framework and Github Actions. Terraform will be added in a subsequent PR. However, changes in preparation for Terraform have been made.

DI-447 Security Scanning of Dockerfiles, Serverless Framework and Github Actions

---

build/docker/tester/Dockerfile

https://nhsd-jira.digital.nhs.uk/browse/DI-454
-
Upgrade Test suite Tester image from python version 3.9 to 3.10.4 thereby taking advantage of some improvement in code efficiency now available via this version.
- Change only occured in the Tester Docker file

DI-454 Upgrade tester image python version

---

test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/change_event.py
test/integration/steps/utilities/events.py

[-](https://nhsd-jira.digital.nhs.uk/browse/DI-453)
Refactoring of some of the change event logic.
- Created a new file called change_event.py and moved some of the event logic from events.py into it.
- Test

DI-453 Refactor of change event generation

---

deployment/serverless.yml
infrastructure/stacks/after-lambda-deployment/providers.tf
infrastructure/stacks/after-lambda-deployment/splunk.tf
infrastructure/stacks/api-key/providers.tf
infrastructure/stacks/appconfig/providers.tf
infrastructure/stacks/before-lambda-deployment/providers.tf
infrastructure/stacks/development-pipeline/build-environment-buildspec.yml
infrastructure/stacks/development-pipeline/delete-task-environment-from-tag-buildspec.yml
infrastructure/stacks/development-pipeline/delete-task-environment-on-pr-merged-buildspec.yml
infrastructure/stacks/dos-api-gateway-mock/providers.tf

This PR is to do some upgrades to our configuration of Serverless Framework and Terraform to hopefully increase the deployment speeds. As wells as deployment removal speeds.

Update Serverless deployment to use direct deployment

---

.github/workflows/code-quality.yml
Makefile
application/comparison_reporting/reporter.py
application/comparison_reporting/tests/test_reporter.py
application/event_processor/changes.py
application/pyproject.toml
application/requirements-dev.txt

- https://nhsd-jira.digital.nhs.uk/browse/DI-448
This PR sets up dead code scanning using Vulture to scan python code for dead code. Also `update_changes_with_address ` is dead code

DI-448 Set up dead code scanning

---

infrastructure/stacks/development-pipeline/development_pipeline_codepipeline.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-458>**
This PR deploys the demo environment straight from the development pipeline

DI-458 Add demo deployment to development pipeline

---

Makefile
application/common/dos.py
application/common/nhs.py
application/common/tests/conftest.py
application/common/tests/test_dos.py
application/comparison_reporting/reporter.py
application/comparison_reporting/run_dentist_reports.py
application/event_processor/tests/test_reporting.py
application/pyproject.toml

**<https://nhsd-jira.digital.nhs.uk/browse/DI-457>**
This PR refactor unused variables in the lambda code.

DI-457 Refactor application code to remove dead code

---

Makefile
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/development_pipeline_codebuild.tf

This PR is to fix the development pipeline (fix is already working in pipeline) so that docker images are pushed with the correct tags.

Fix development pipelines and Remove duplicated make targets

---

test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-466>**

DI-466 Remove redundant utils function

---

Makefile
build/automation/var/project.mk
infrastructure/stacks/development-pipeline/build-buildspec.yml
infrastructure/stacks/development-pipeline/build-image-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DI-467>**
This PR is to add a make target to check the ECR Image scan reports to find vulnerabilities. So if an unacceptable vulnerability is found the pipeline is exited and the environments are not deployed.

DI-467 Check ECR scanning reports for vulnerabilities 

---

.github/workflows/update-pull-request-description.yml
.gitignore
Makefile
application/common/tests/conftest.py
application/common/tests/test_appconfig.py
application/common/tests/test_middlewares.py
application/common/tests/test_utilities.py
application/dos_api_gateway/dos_api_gateway.py
application/dos_api_gateway/tests/test_dos_api_gateway.py
application/event_replay/tests/test_event_replay.py
application/event_sender/change_request_logger.py
application/event_sender/tests/test_change_request.py
application/event_sender/tests/test_change_request_logger.py
application/orchestrator/orchestrator.py
application/slack_messenger/slack_messenger.py
application/slack_messenger/tests/test_slack_messenger.py
build/automation/var/project.mk
build/docker/lambda/Dockerfile
build/docker/tester/Dockerfile
pytest.ini

This PR is to fix a Github Action and improve unit test coverage. As well there are some simplifying of build steps.

Fix Github Workflows and Improve Unit Test Coverage

---

.github/workflows/update-pull-request-description.yml
infrastructure/stacks/after-lambda-deployment/cloudwatch.tf

This PR is to do two things:
- Firstly update cloudwatch resources to be more helpful. An additional query has been created which is easier for reading the messages and the dashboard has been changed to show data as dots rather than lines.
- Secondly a fix to the PR update description action to fix a bug where it using the branch name rather than designation

Update Cloudwatch dashboard and queries

---

test/integration/features/F006_Opening_times.feature
test/integration/steps/test_parent_steps.py
test/integration/steps/utilities/utils.py

This test adds a new function to utils based off code in a previous test that isn't present in this branch.
It also adds 2 tests for pharmacies when the closing time is the same as the opening time for a split day.

DI-490 Integration tests for same closing and opening time

---

build/automation/var/platform-texas/v1/account-live-k8s-nonprod.mk
build/automation/var/platform-texas/v1/account-live-k8s-prod.mk
infrastructure/stacks/before-lambda-deployment/data.tf
infrastructure/stacks/before-lambda-deployment/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-482>**
This PR allows developers to access the DB Clone as it is protected by a KMS Key

DI-482 Dynamodb Cloner Kms Key Access

---

.github/workflows/code-quality.yml
application/scripts/dynamodb_to_csv.py

This PR is to add a python script to allow downloading a dynamodb table to csv to allow for easy interaction with the data from the dynamodb table

Add Python Script for downloading a Dynamodb Table to CSV

---

application/common/opening_times.py
application/common/tests/test_opening_times.py
application/event_processor/changes.py
application/event_processor/tests/test_changes.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-472>**
Removes past specified dates from incomming change events

DI-472 Add change to remove specified dates in the past

---

application/event_processor/reporting.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-493>**
2 new splunk reports have been made to gather generic errors from DI.
For this report, generic columns are needed to describe what each error is about. These are error_reason and error_info.
These 2 fields have been added into the log code for an invalid website with the specific information on this error type.
Future error logs can be added to the same report in a similar way when using the same report key and adding their own information to these 2 fields.

DI-493 Create generic error report

---

test/integration/features/F004_Error_Handling.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DI-493>**
This fixes the integration test which is checking the incorrect field.

Fix Invalid Website Integration Test

---

infrastructure/stacks/release-pipeline/codepipeline.tf

This PR is to fix the release pipeline, this change has already been applied to `release/2.0.0` release pipeline

Fix Release Branch Pipeline

---

application/event_processor/changes.py
application/event_processor/tests/test_changes.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-478>**
This PR makes all fields in the address title case. This means that `Address1`, `Address2`, `Address3`, `City` and `County` are all converted to title case.

DI-478 Update Address received from NHS.UK to title case

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-498>**
Integration Tests for DI-478

DI-498 Tests for title case address

---

Makefile
build/automation/var/project.mk
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-release-environment-and-pipeline-on-pr-merged-buildspec.yml
infrastructure/stacks/development-pipeline/tag-release-images-on-branch-delete-buildspec.yml
infrastructure/stacks/development-pipeline/tag_release_images_on_branch_delete.tf

Ignore This - Testing release delete codebuild stage

---

Makefile
build/automation/var/project.mk
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/delete-release-environment-and-pipeline-on-pr-merged-buildspec.yml
infrastructure/stacks/development-pipeline/tag-release-images-on-branch-delete-buildspec.yml
infrastructure/stacks/development-pipeline/tag_release_images_on_branch_delete.tf

Please don't modify this description yet it will be populated once you create the pull request.

Re tag images when the release branch is deleted

---

infrastructure/stacks/after-lambda-deployment/alerts.tf
infrastructure/stacks/before-lambda-deployment/data.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-475>**
This PR is to add a new cloudwatch alarm to alert when the DoS API Gateway returns a 400. As well this branch fixes the alarms which are now mostly not working in live

DI-475 Update cloudwatch alarms for slack

---

Makefile
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F003_DoS_Security.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/steps/test_steps.py
test/integration/steps/utilities/utils.py

- DI-475
These changes create some new functionality for the Integration Suite.
There is now a function that can send messages directly into SQS queues.
There is now a function that can check Slack channels to ensure that the alerts are being sent.

DI-488 Sqs and slack alert test cases

---

test/integration/steps/utilities/utils.py

- This change is not associated with a branch
Why do these tests need to exist?/When should the test be run?
This is just a timing change for the existing tests. No changes have been made for the tests. Cloudwatch alarms are to be updated to cover 5 minute periods instead of 2 minute periods, so the catch timings need to be longer for these to guarantee appearing.

DI-537 Slack timing update for cloudwatch changes

---

Makefile
application/common/opening_times.py
application/common/tests/test_opening_times.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
application/service_sync/service_sync.py
application/service_sync/tests/test_service_sync.py
infrastructure/stacks/after-lambda-deployment/cloudwatch-alarms.tf
infrastructure/stacks/after-lambda-deployment/cloudwatch-dashboard.tf
infrastructure/stacks/after-lambda-deployment/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-533>**
This PR is to create custom metrics/alarms and graphs on the cloudwatch dashboard for the new architecture 

DI-533 Update Cloudwatch Dashboard and Add New Cloudwatch Alarms

---

build/automation/var/project.mk
test/integration/features/F005_Support_Functions.feature
test/integration/steps/test_steps.py
test/integration/steps/utilities/utils.py

- DI-553 is branched off DI-519
Why do these tests need to exist?/When should the test be run?
This ticket involves fixing and rewording existing test cases for work completed in DI-519.

DI-553 Update sqs test failures

---

.github/workflows/code-quality.yml
.github/workflows/python-code-quality.yml
Makefile
application/common/dos.py
application/common/dynamodb.py
application/pyproject.toml
application/requirements-dev.txt
application/service_sync/dos_data.py
application/service_sync/service_histories.py
application/service_sync/tests/test_dos_data.py
application/service_sync/tests/test_service_histories.py
infrastructure/stacks/development-pipeline/development_pipeline_codebuild.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-546>**
This PR is to run vulnerability/security testing on the Python code.

DI-546 Python Security Scanning

---

application/common/dos_db_connection.py
application/common/dynamodb.py
application/common/tests/test_dos_db_connection.py
application/common/tests/test_utilities.py
application/common/types.py
application/common/utilities.py
application/orchestrator/orchestrator.py
application/orchestrator/requirements.txt
application/pyproject.toml
application/service_matcher/tests/test_service_matcher.py
application/service_sync/dos_data.py
application/service_sync/service_sync.py
application/service_sync/tests/test_dos_data.py
application/service_sync/tests/test_service_sync.py
deployment/serverless.yml
infrastructure/stacks/after-lambda-deployment/cloudwatch-alarms.tf
infrastructure/stacks/after-lambda-deployment/cloudwatch-dashboard.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-534>**
This PR re-implements the health check but now checks both the DoS DB and Replica so that DI automatically stops sending messages to DoS when either DB is broken

DI-534 Handle DoS DB Failures

---

application/common/opening_times.py
application/common/tests/test_opening_times.py
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-544>**

DI-544 Fixed hash bug for Specified Open Times

---

README.md
application/common/opening_times.py
application/common/tests/test_opening_times.py
application/common/utilities.py
application/service_sync/changes_to_dos.py
application/service_sync/dos_data.py
application/service_sync/dos_logger.py
application/service_sync/service_histories.py
application/service_sync/service_histories_change.py
application/service_sync/tests/test_changes_to_dos.py
application/service_sync/tests/test_dos_logger.py
build/automation/var/project.mk
infrastructure/stacks/after-lambda-deployment/data.tf
infrastructure/stacks/after-lambda-deployment/splunk.tf
infrastructure/stacks/after-lambda-deployment/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-524>**
This PR adds a python class to create special logs for the DoS Splunk index with a kinesis firehose to get the cloudwatch logs to go to Splunk

DI-524 Log Service Update to DoS

---

application/common/dos_db_connection.py
application/service_sync/changes_to_dos.py
application/service_sync/dos_data.py
test/integration/features/F006_Opening_times.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DI-573>**
This PR fixes minor bugs in the application that cause tests to not work in the pipeline

Fix application bugs

---

application/service_sync/service_histories.py
application/service_sync/service_histories_change.py
application/service_sync/tests/test_service_histories_change.py
test/integration/steps/test_steps.py
test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-578>**
This PR changes the action type remove to delete so both DI and DoS use the same values for the same action 
Test Results:

DI-578 Change the change action from remove to delete

---

application/common/utilities.py
application/dos_db_update_dlq_handler/dos_db_update_dlq_handler.py
application/dos_db_update_dlq_handler/tests/test_dos_db_update_dlq_handler.py
application/service_sync/service_sync.py
application/service_sync/tests/test_service_sync.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-541>**
This PR is to add a couple of additional metrics to count the number of success and failed updates for services

DI-541 Add additional metrics for splunk dashboards

---

README.md

This is an update of the documentation to reflect how DI and the DI team currently operate

Improve DoS Integration Documentation

---

infrastructure/stacks/development-pipeline/locals.tf

This PR is to add send-email to the development pipeline to fix deployments

Fix development pipeline

---

application/service_sync/service_histories_change.py
application/service_sync/service_update_logging.py
application/service_sync/tests/test_service_histories_change.py
infrastructure/stacks/development-pipeline/deploy-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DI-592>**
This PR fixes bugs which have caused issue for the performance tests.

DI-592 Fix a couple of bugs

---

build/automation/var/profile/demo.mk
build/automation/var/profile/live.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DI-523>**
This PR updates the profiles for production so they should be able to access the new roles

DI-523 Update Production profiles for release 3.0

---

build/docker/serverless/Dockerfile
deployment/serverless.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DI-606>**
This PR is to fix production deployments by making the dos-db-handler lambda only deploy in nonprod environments

DI-606 Fix production deployments

---

infrastructure/stacks/before-lambda-deployment/lambda_security_groups.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-523>**
This PR is to allow an inbound rule to the replica security group as the RDS has different configuration in prod

DI-523 Add second sg inbound rule for replicas in specific environments

---

infrastructure/stacks/before-lambda-deployment/lambda_security_groups.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-523>**
Fixes the incorrect Terraform conditional which should have been an OR but was incorrectly put as an AND

DI-523 Fix incorrect Terraform condition

---

application/pyproject.toml
application/service_sync/changes_to_dos.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-591>**
This PR turns off address formatting in both the application and integration tests

DI-591 Disable address formatting

---

application/common/middlewares.py
application/common/tests/test_middlewares.py
application/common/types.py
application/send_email/send_email.py
application/send_email/tests/test_send_email.py
application/service_sync/pending_changes.py
application/service_sync/tests/test_pending_changes.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-595>**
This PR stops PID from being shown when an error occurs in the send email lambda. Also it improves logging for easier debugging.

DI-595 Fix exception being logged with PID

---

Makefile
build/automation/var/platform-texas/v1/account-live-k8s-nonprod.mk
build/automation/var/platform-texas/v1/account-live-k8s-prod.mk
build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/nonprd.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/task.mk
build/automation/var/profile/test.mk
build/automation/var/project.mk
deployment/serverless.yml
infrastructure/stacks/before-lambda-deployment/data.tf
infrastructure/stacks/before-lambda-deployment/variables.tf
infrastructure/stacks/common/common-provider.tf
infrastructure/stacks/common/common-variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-550>**
This PR adds the required tags for the new Texas Tagging guidance

DI-550 Add more tags to Terraform and Serverless Framework

---

application/pyproject.toml
application/service_sync/changes_to_dos.py
application/service_sync/service_histories.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-607>**
This PR turns back on address formatting and it's tests

DI-607 Turn back on address formatting

---

build/automation/var/project.mk
deployment/serverless.yml
infrastructure/stacks/after-lambda-deployment/cloudwatch-alarms.tf
infrastructure/stacks/after-lambda-deployment/data.tf
infrastructure/stacks/after-lambda-deployment/variables.tf
infrastructure/stacks/before-lambda-deployment/kms.tf
infrastructure/stacks/before-lambda-deployment/new_lambda_iam_roles.tf
infrastructure/stacks/before-lambda-deployment/sns.tf
infrastructure/stacks/before-lambda-deployment/variables.tf
infrastructure/stacks/common/common-provider.tf
infrastructure/stacks/common/common-variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-561>**
This PR renames the alarm region variable to something more descriptive

DI-561 Rename alarm region variable

---

infrastructure/stacks/common/common-variables.tf
infrastructure/stacks/deployment-pipelines/live_codebuild.tf
infrastructure/stacks/release-pipeline/data.tf

This PR is to fix a couple of issues found when deploying the Release Development Pipeline.

Fix Release Pipeline Terraform

---

application/service_sync/changes_to_dos.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-637>**
This PR is to hotfix the specified opening times bug where a equal DoS and NHS UK specified opening times are considered not equal

Hotfix 3.1

---

application/change_event_dlq_handler/requirements.txt
application/dos_db_handler/requirements.txt
application/dos_db_update_dlq_handler/requirements.txt
application/event_replay/requirements.txt
application/orchestrator/requirements.txt
application/send_email/requirements.txt
application/service_matcher/requirements.txt
application/service_sync/requirements.txt
application/slack_messenger/requirements.txt

**<https://nhsd-jira.digital.nhs.uk/browse/DI-651>**
This PR sets the AWS Powertools Python version to 1.31.1 so that the code currently works. In DI-639 the version will be upgraded to a new minified version.

DI-651 Set AWS PowerTools Python Version 

---

application/change_event_dlq_handler/change_event_dlq_handler.py
application/common/dynamodb.py
application/dos_db_handler/dos_db_handler.py
application/dos_db_update_dlq_handler/dos_db_update_dlq_handler.py
application/event_replay/event_replay.py
application/orchestrator/orchestrator.py
application/orchestrator/tests/test_orchestrator.py
application/send_email/send_email.py
application/send_email/tests/test_send_email.py
application/service_matcher/service_matcher.py
application/service_sync/service_sync.py
application/service_sync/tests/test_service_sync.py
application/service_sync/tests/test_service_update_logging.py
application/slack_messenger/slack_messenger.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-641>**

DI-641 Service sync log carry over

---

infrastructure/stacks/development-pipeline/build-cicd-artefact-buildspec.yml
infrastructure/stacks/development-pipeline/build_cicd_artefact.tf
infrastructure/stacks/development-pipeline/cicd_pipeline.tf
infrastructure/stacks/development-pipeline/data.tf
infrastructure/stacks/development-pipeline/development_pipeline_codepipeline.tf
infrastructure/stacks/development-pipeline/main.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-617>**
This PR adds a codebuild stage that will zip the repository and store the folder in S3.

DI-617 Create a Build Artefact and store in S3

---

Makefile

**<https://nhsd-jira.digital.nhs.uk/browse/DI-617>**
Fixes incorrect appconfig name which is used by the integration tests

DI-617 Fix incorrect appconfig name

---

test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-656>**
This PR adds test scenarios to cover the bug DI-641
- New Tests

DI-656 Test scenarios for 641 added

---

infrastructure/stacks/after-lambda-deployment/route53.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-659>**
This PR removes the Route53 Health Check default address and replaces it with a variable.

DI-659 Remove Route53 Health Check default value

---

application/service_sync/changes_to_dos.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-660>**
Apply the hotfix code from 3.1 to develop

DI-660 Apply hotfix 3.1 to develop

---

infrastructure/stacks/development-pipeline/build-cicd-shared-resources-artefact-buildspec.yml
infrastructure/stacks/development-pipeline/build_cicd_shared_resources_artefact.tf
infrastructure/stacks/development-pipeline/cicd_shared_resources_pipeline.tf
infrastructure/stacks/development-pipeline/data.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-619>**
This PR add a codebuild stage to build a zip file for the shared resources pipeline that is yet to be built. 

DI-619 Add codebuild stage to trigger shared resources pipeline

---

infrastructure/stacks/shared-resources/api-gateway-responses.tf
infrastructure/stacks/shared-resources/api-gateway.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-577>**
This PR hides the response when a user sends a change event to the DI endpoint with an IP which isn't on the allowlist

DI-577 Hide API Gateway responses

---

application/dos_db_handler/dos_db_handler.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F005_Support_Functions.feature
test/integration/steps/test_steps.py
test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-655>**
New tests created from hotfix 3.1
- Tests

DI-655 Test scenarios for hotfix 3.1

---

infrastructure/stacks/development-and-deployment-tools/cicd_blue_green_deployment_pipeline.tf
infrastructure/stacks/development-and-deployment-tools/cicd_shared_resources_pipeline.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-648>**
This change allows deployment to the live environment from both the Shared Resources CI/CD Pipeline or the Blue/Green CI/CD Pipeline

DI-648 Set Up Live Deployment Pipelines

---

Makefile
README.md
infrastructure/stacks/blue-green-link/parameter_store.tf
infrastructure/stacks/development-and-deployment-tools/buildspecs/rollback-blue-green-deployment-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/cicd_blue_green_rollback.tf
infrastructure/stacks/development-and-deployment-tools/data.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DI-671>**
This PR allows rollbacks of blue/green demo deployments

DI-671 Deployment Rollback Stage

---

.github/workflows/codeql-analysis.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DI-688>**
This PR adds a workflow which runs CodeQL to analyse the security of the project.

DI-688 Add CodeQL Analysis

---

infrastructure/modules/lambda-iam-role/main.tf
test/integration/README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DI-681>**
This change adds a readme file to the test/integration folder that has some information about the integration test suite
- Documentation

DI-681 Integration suite readme file

---

test/integration/features/F001_Valid_Change_Events.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DI-696>**
Test case uses last year in automatic date generation, and the year has changed so test case needs updating.
- Test

DI-696 Update test case so that year is valid

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F005_Support_Functions.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DI-697>**
This is a change to F1S17 to utilise DOS DB checks instead of log checks
- Test Update

DI-697 Update past date test to assert against db

---

test/integration/features/F006_Opening_times.feature
test/integration/steps/test_steps.py
test/integration/steps/utilities/generator.py

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-40>**
This is a change to add in two new tests to validate the functionality in release 2.1 where there was currently no test case in the integration suite. The tests ensure that an additional date can be opened or closed on the same date and have changes recognised. There is another test that also verifies the opening times changes in the same circumstances.
- Test

DSUEC-40 Added tests for 2.1 Release

---

infrastructure/stacks/before-lambda-deployment/data.tf
infrastructure/stacks/before-lambda-deployment/lambda_security_groups.tf
infrastructure/stacks/before-lambda-deployment/variables.tf
infrastructure/stacks/shared-resources/data.tf
infrastructure/stacks/shared-resources/route53.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-38>**
Replace the Texas Terraform Remote state data sources with AWS resource data sources.

DSUEC-38 Remove Reliance on Texas Remote State

---

infrastructure/stacks/development-and-deployment-tools/build_environment.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-61>**
This PR allows branches to now be named task/DSUEC-xx_branch_name and it create an environment

DSUEC-61 Update Build Environment Codebuild to Deploy New Branch Prefix

---

infrastructure/stacks/development-and-deployment-tools/buildspecs/build-release-buildspec.yml
infrastructure/stacks/release-pipeline/codepipeline.tf
infrastructure/stacks/release-pipeline/data.tf
infrastructure/stacks/release-pipeline/locals.tf
infrastructure/stacks/release-pipeline/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-58>**
This PR fixes the pre-release pipeline deployment when a release branch is created.

DSUEC-58 Fix pre-release pipeline

---

infrastructure/stacks/development-and-deployment-tools/development_pipeline.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-62>**
This PR allows development pipeline to deploy to demo after the integration tests have passed.

DSUEC-62 Set Development Pipeline to deploy to demo

---

application/slack_messenger/slack_messenger.py
application/slack_messenger/tests/test_slack_messenger.py
infrastructure/stacks/development-and-deployment-tools/development_pipeline.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-63>**
Allow Slack Messenger to handle alarms from expressions as well as some refactoring of the Slack Messenger

DSUEC-63 Allow Slack Messenger to Handle Expression Alerts

---

infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-81>**
Deploy alarm in nonprod so integration tests pass

DSUEC-81 Fix Alarm Integration Test

---

README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-93>**
Updates the release documentation to add missed information.

DSUEC-93 Update Release Documentation

---

Makefile
README.md
application/slack_messenger/tests/test_slack_messenger.py
infrastructure/stacks/development-and-deployment-tools/build_environment.tf
infrastructure/stacks/development-and-deployment-tools/buildspecs/delete-nonprod-environment-on-pr-merged-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_on_pr_merged.tf
test/integration/README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-72>**
This PR fixes the codebuild stage which deletes nonprod environments after a PR is merged ensuring less effort in cleaning up environments. As well I have transitioned all DI-xxx branch name references to dsuec

DSUEC-72 Fix Nonprod Environment Removal Stage

---

build/automation/var/profile/demo.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-94>**
This PR migrates all demo environments to now connect to UAT2 database.

DSUEC-94 Migrate Demo to point to UAT2

---

build/automation/etc/githooks/pre-commit
infrastructure/stacks/blue-green-link/cloudwatch-dashboard.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-95>**
This PR updates the CloudWatch Dashboard to be more useful. Such as adding a graph, adding metrics as labels.

DSUEC-95 Improve dashboard with new metrics and labels

---

.github/workflows/pull-request.yml

This PR stops the release branch from failing the branch checks

Update GitHub Actions for Releases

---

infrastructure/stacks/development-and-deployment-tools/buildspecs/deploy-blue-green-environment-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-105>**
This PR fixes the source version for removing blue/green environment to ensure the right parameters are passed to the codebuild stage.

DSUEC-105 Fix Source Version for Removing Blue/Green Environments

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/project.mk
infrastructure/stacks/before-lambda-deployment/data.tf
infrastructure/stacks/before-lambda-deployment/lambda_security_groups.tf
infrastructure/stacks/before-lambda-deployment/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-121>**
This PR updates the terraform to use security group names to get the security group id rather than getting the security group id from the RDS connected security groups.

DSUEC-121 Database Security Group Lookup

---

application/common/dos.py
application/common/dos_db_connection.py
application/common/tests/test_dos.py
application/common/tests/test_dos_db_connection.py
application/dos_db_handler/dos_db_handler.py
application/dos_db_handler/requirements.txt
application/service_matcher/requirements.txt
application/service_sync/dos_data.py
application/service_sync/pending_changes.py
application/service_sync/requirements.txt
application/service_sync/service_histories.py
application/service_sync/tests/test_service_histories.py
infrastructure/stacks/before-lambda-deployment/lambda_security_groups.tf
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_times.feature
test/integration/steps/test_steps.py
test/integration/steps/utilities/generator.py
test/integration/steps/utilities/utils.py

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-120>**
This PR updates pyscopg2 to psycopg3 which is now called pyscopg (lol) Also I've made minor changes to made it work.

DSUEC-120 Upgrade Psycopg Version

---

.github/workflows/code-quality.yml
README.md
build/docker/lambda/Dockerfile

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-117>**
This PR upgrades DI's AWS Lambdas to use Python 3.10 with all the benefits of it such as better error tracing and slightly improved performance.

DSUEC-117 Upgrade Python Version to 3.10

---

Makefile
build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-75>**
Update the setup and configuration of the application to use Route 53 address when connection to the DoS databases

DSUEC-75 Route 53 address for DoS database connections

---

infrastructure/stacks/before-lambda-deployment/lambda_iam_roles.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-127>**

DSUEC-127 Allow Lambdas to be able to access DynamoDB Backups

---

application/common/nhs.py
application/common/report_logging.py
application/common/tests/test_nhs.py
application/service_sync/compare_data.py
application/service_sync/tests/test_compare_data.py

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-109>**
This PR skips the palliative care checks when Palliative Care has never been set on Profile Manager

DSUEC-109 Skip Palliative Care Check

---

application/requirements-dev.txt

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-125>**
Pin back Bandit Version to 1.7.4

DSUEC-125 Pin Bandit Version

---

.github/workflows/codeql-analysis.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-577>**
This PR enhances to CodeQL Vulnerability Scanning to run more security checks as well as quality checks.

DSUEC-577 Increase CodeQL Vulnerability Scanning

---

application/common/dos.py
application/requirements-dev.txt
application/service_sync/pending_changes.py
application/service_sync/tests/test_pending_changes.py
application/slack_messenger/slack_messenger.py
application/slack_messenger/tests/test_slack_messenger.py

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-504>**
This PR fixes the latest warning messages from bandit

DSUEC-504 Fix Security Warning Messages

---

application/common/report_logging.py
application/common/tests/test_report_logging.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-129>**
This PR updates to code to Log only Type 13 to Unexpected Pharmacy Profiling Report when multiple type 13s are present.

DSUEC-129 Log only Type 13 to Unexpected Pharmacy Profiling Report

---

infrastructure/stacks/shared-resources/api-gateway-responses.tf
infrastructure/stacks/shared-resources/api-gateway.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-511>**
This PR adds security headers for the DI Endpoint API Gateway

DSUEC-511 Add security headers to API Gateway

---

build/automation/var/project.mk
deployment/serverless.yml
infrastructure/modules/s3/main.tf
infrastructure/modules/s3/variables.tf
infrastructure/stacks/shared-resources/s3.tf
infrastructure/stacks/shared-resources/variables.tf
test/integration/steps/conftest.py
test/integration/steps/utilities/generator.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-513>**
Add Server Access Logging for the send email bucket

DS-513 Add Server Access Logging

---

application/common/report_logging.py
application/common/tests/test_report_logging.py
application/service_sync/dos_data.py
application/service_sync/tests/test_dos_data.py
infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-106>**
This PR validates that an SDSGID exists within the database. If it doesn't it logs to the generic error report and alerts to the slack channel.

DSUEC-106 Validate SDSGID Combination

---

application/common/s3.py
application/common/tests/test_s3.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-638>**
This PR encrypts objects uploaded to the S3 send email bucket.

DS-638 Add Object Encryption to File Upload

---

build/automation/var/profile/demo.mk
build/automation/var/profile/live.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-673>**
This PR reverts back to previous db endpoints

DS-673 Revert Back to Previous DoS DB Endpoints

---

infrastructure/modules/s3/main.tf
infrastructure/modules/s3/variables.tf
infrastructure/stacks/shared-resources/s3.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-705>**
This PR fixes an issue with the S3 ACL/object ownership configuration.

DS-705 Fix Bucket Acl Issue

---

infrastructure/stacks/shared-resources/s3.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-705>**
This PR removes the Server Access Logging bucket to remove the issue with ACLs. This feature will be restored after release 12.

DI-705 Disable Logging Bucket

---

infrastructure/stacks/shared-resources/s3.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-705>**
This PR fixes where the send email bucket is dependant on the commented out logging bucket.

DS-705 Fix Depends On Removed Resources

---

build/automation/var/profile/perf2.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-711>**
This PR fixes the perf2 environment configuration.

DS-711 Update Perf2 profile

---

documentation/adr/010-Improve-Application-Performance.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-128>**
This PR adds an architectural decision record to explain the decision to remove the orchestrator to improve performance.

DS-128 Add Improving Performance ADR

---

application/ingest_change_event/ingest_change_event.py
application/service_sync/service_sync.py
application/service_sync/service_update_logging.py
application/service_sync/tests/test_service_update_logging.py
build/automation/var/project.mk
infrastructure/stacks/blue-green-link/cloudwatch-dashboard.tf
infrastructure/stacks/blue-green-link/cloudwatch-queries.tf
infrastructure/stacks/blue-green-link/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-747>**
This PR adds a Data Item metric to show what is being updated. This is on a per data item being updated so if postcode is updated, town, easting, northing, latitude and longitude updates are also recorded.

DS-747 Add Data Item Update Metrics

---

infrastructure/stacks/shared-resources/s3.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-707>**
This PR adds server access logging to the send email bucket that follows the new AWS policies.

DS-707 Add Server Access Logging

---

Makefile
application/requirements-dev.txt
pyproject.toml
test/integration/steps/conftest.py
test/integration/steps/test_steps.py
test/integration/steps/utilities/cloudwatch.py
test/integration/steps/utilities/constants.py
test/integration/steps/utilities/context.py
test/integration/steps/utilities/generator.py
test/integration/steps/utilities/secrets_manager.py
test/integration/steps/utilities/translation.py
test/integration/steps/utilities/utils.py
test/performance/create_change_events/aws.py
test/performance/create_change_events/load_test_locustfile.py
test/performance/create_change_events/stress_test_locustfile.py
test/performance/create_change_events/utilities.py
test/pyproject.toml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-774>**
This PR fixes F001SXX3 integration test by making the assertion work. As well making the comparison values correct for the assertion.

DS-774 Broken F001SXX3 Integration Test

---

Makefile
application/common/dos.py
application/common/report_logging.py
application/common/tests/test_dos.py
application/common/tests/test_report_logging.py
application/requirements-dev.txt
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
application/service_sync/compare_data.py
application/service_sync/tests/test_compare_data.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F003_DoS_Security.feature
test/integration/features/F004_Error_Handling.feature
test/integration/steps/pytest.ini
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-817>**
This PR migrates the Blank Opening Time report from the service matcher to the service sync. As well as adding the service region to the report. This PR also does some clean up of the test dentist code.

DS-817 Add Region to Blank Opening Times Report

---

build/automation/var/profile/demo.mk
build/automation/var/profile/live.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-692>**
This PR re-applies the profiles for the Route 53 and SG which will connect to Aurora.

DS-692 Update Profiles for Aurora Connections

---

test/integration/steps/utilities/cloudwatch.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-928>**
This PR improves Integration Test resiliency to add retries to the CloudWatch Log insights Query when multiple tests run at the same time.

DS-928 Log Insights Query Retry Process

---

application/common/dos.py
application/common/nhs.py
application/common/tests/test_dos.py
application/event_replay/event_replay.py
application/event_replay/tests/test_event_replay.py
application/service_matcher/reporting.py
application/service_matcher/tests/test_reporting.py
application/service_sync/compare_data.py
application/service_sync/dos_data.py
application/service_sync/reporting.py
application/service_sync/service_update_logging.py
application/service_sync/tests/test_compare_data.py
application/service_sync/tests/test_dos_data.py
application/service_sync/tests/test_reporting.py
application/service_sync/tests/test_service_update_logging.py
application/service_sync/tests/test_validation.py
application/service_sync/validation.py
test/integration/features/F007_Reporting.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-818>**
This PR adds additional attributes to report logs for better formatting and to make the reports more informative.

DS-818 Update Service Sync Reports

---

.github/dependabot.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-961>**
This PR cleans up the Dependabot configuration by adding and removing Terraform stacks.

DS-961 Update Dependabot Configuration

---

application/ingest_change_event/appconfig.py
application/ingest_change_event/tests/test_appconfig.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-930>**
This PR increases AppConfig's cache time to reduce cost during performance tests.

DS-930 Reduce AppConfig Costs

---

Makefile
build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk
build/automation/var/project.mk
deployment/serverless.yml
infrastructure/stacks/before-lambda-deployment/lambda_iam_roles.tf
infrastructure/stacks/development-and-deployment-tools/buildspecs/production-smoke-test-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/development_pipeline.tf
infrastructure/stacks/development-and-deployment-tools/production_smoke_test.tf
test/smoke/functions/service.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-962>**
This PR applies the production smoke test to the development pipeline.

DS-962 Add Production Smoke Test to Development Pipeline

---

application/common/dos.py
application/common/tests/test_dos.py
application/service_matcher/reporting.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_reporting.py
application/service_matcher/tests/test_service_matcher.py
application/service_sync/dos_data.py
infrastructure/stacks/development-and-deployment-tools/build_and_test_environment.tf
test/integration/features/F007_Reporting.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-771>**
This PR adds additional attributes to report logs for better formatting and to make the reports more informative.

DS-771 Update Service Matcher Reports

---

infrastructure/stacks/development-and-deployment-tools/development_pipeline.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1003>**
This PR fixes the smoke test not working in the development pipeline.

DS-1003 Fix Development Pipeline Smoke Test

---

Makefile
build/automation/var/profile/perf2.mk
build/automation/var/project.mk
infrastructure/stacks/shared-resources/data.tf
infrastructure/stacks/shared-resources/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-690>**
This PR changes to application to allow the new SSO roles to deploy the application.

DS-690 Migrate to SSO roles

---

infrastructure/stacks/appconfig/appconfig.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1149>**
This PR adds infrastructure for service matcher feature flags. This allows selectively allowing service types to be matched and processed.

DS-1149 Add Infrastructure For Service Matcher Feature Flags

---

infrastructure/stacks/shared-resources/api-gateway.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-512>**
This PR sets an API Gateway Rate Limit.

DS-512 Set API Gateway Rate Limit

---

infrastructure/stacks/blue-green-link/cloudwatch-queries.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1218>**
This PR renames some of the CloudWatch queries to make the names simpler and more understandable.

DS-1218 Update CloudWatch Query Names

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1221>**
This PR speeds up the task deploy and test by separating the integration tests by the tag to run more tests in parallel

DS-1221 Speed Up Integration Tests in Task Deploy and Test

---

application/common/dos.py
application/common/tests/test_dos.py
application/service_matcher/reporting.py
application/service_matcher/tests/test_reporting.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-980>**
This PR allows the service status key for the hidden or closed report to show the real service status.

DS-980 Set Service Status in Reports using Database Value

---

application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
test/integration/features/F001_Valid_Change_Events.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1186>**
This PR adds checks to ensure any services are active before allowing matched services to be processed.

DS-1186 Only Process Services If Any Are Active

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1241>**
This PR fixes a test bug where the integration tests reused the same odscode therefore increase the number of matched services with each test run.

DS-1241 Fix Integration Test ODSCode Bug

---

infrastructure/stacks/before-lambda-deployment/data.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1271>**
This PR is to remove the Terraform reliance on RDS instances.

DS-1271 Remove Reliance on RDS Instances

---

infrastructure/stacks/before-lambda-deployment/data.tf

This PR releases 17.1 which removes DI's reliance on DoS RDS instances.

Release 17.1 Remove Reliance on RDS Instances

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk
build/automation/var/project.mk
infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf
infrastructure/stacks/blue-green-link/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1262>**
This PR updates the AWS CloudWatch dashboards to show Aurora db stats such as CPU utilisation and DB connections.

DS-1262 Show Aurora DBs Stats on CloudWatch Dashboard

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-batch-jobs/deploy-task-environment.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1305>**
This PR pulls the Serverless image after the docker user has been logged in.

DS-1305 Test Docker Image Pulling Improvement

---

.github/workflows/code-quality.yml
.github/workflows/code-secrets.yml
.github/workflows/code-security.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/pull-request.yml
.github/workflows/python-code-quality.yml
.github/workflows/update-pull-request-description.yml
infrastructure/stacks/before-lambda-deployment/lambda_iam_roles.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1315>**
Remove unused AppConfig permissions from a lambda role. As well it includes a GitHub actions checkout update/

DS-1315 Remove Unused AppConfig Permissions

---

application/common/dos.py
application/common/nhs.py
application/common/tests/test_dos.py
application/common/tests/test_nhs.py
application/service_matcher/reporting.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_reporting.py
application/service_sync/changes_to_dos.py
application/service_sync/compare_data.py
application/service_sync/dos_data.py
application/service_sync/reporting.py
application/service_sync/service_update_logging.py
application/service_sync/tests/test_compare_data.py
application/service_sync/tests/test_dos_data.py
application/service_sync/tests/test_service_update_logging.py
application/service_sync/tests/test_validate_dos_data.py
application/service_sync/validate_dos_data.py
infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
test/integration/steps/conftest.py
test/integration/steps/functions/generator.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-987>**
This PR allows the blood pressure service to be activated and closed on DoS.

DS-987 Apply Blood Pressure Service

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/functions/constants.py
test/integration/steps/functions/dos/get_data.py
test/integration/steps/functions/dos/translation.py
test/integration/steps/functions/generator.py
test/integration/steps/test_steps.py
test/smoke/functions/aws.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1284>**
- These tests the adding and removal of the blood pressure service. As well as adding the Z code if required.
Regression tests to cover most blood pressure changing and not changing conditions.

DS-1284 Blood Pressure Integration Tests

---

infrastructure/stacks/before-lambda-deployment/variables.tf
infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1328>**
This PR improves the CloudWatch Dashboard to display benchmarks for SLAs and other warnings by using a CloudWatch graph threshold.

DS-1328 Improve CloudWatch Dashboards

---

infrastructure/stacks/development-and-deployment-tools/buildspecs/delete-blue-green-environment-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1348>**
This PR resolves and issue with the blue/green environment cleanup job where it would error on non existent resources. This removes resource dependencies on other teams.

DS-1348 Fix Blue Green Cleanup Job

---

build/automation/var/profile/dev.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1331>**
This PR points all development environments to use the new Regression Aurora database instance

DS-1331 Point Dev to Regression Aurora

---

build/automation/var/profile/demo.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1375>**
Switches demo to use DoS UAT3

DS-1375 Point demo at UAT3 database schema

---

test/performance/functions/performance_test.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1403>**
Add the Palliative Care test back into the performance test suite now that the Z code exists in the performance environments

DS-1403 Add Palliative Care Performance Test

---

application/common/dos.py
application/common/tests/test_dos.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
test/integration/features/F001_Valid_Change_Events.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1162>**
This PR discards non active Blood Pressure and Contraception services when the services aren't being turned to active.

DS-1162 Discard Non Active Services

---

application/service_matcher/reporting.py
application/service_matcher/tests/test_reporting.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F007_Reporting.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1303>**
This PR adds new integration tests for DS-1162.

DS-1303 Add Integration Tests for DS-1162

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/build_cicd_blue_green_deployment_artefact.tf
infrastructure/stacks/development-and-deployment-tools/build_cicd_shared_resources_artefact.tf
infrastructure/stacks/development-and-deployment-tools/build_deploy_test_release.tf
infrastructure/stacks/development-and-deployment-tools/build_tools_image.tf
infrastructure/stacks/development-and-deployment-tools/cicd_blue_green_rollback.tf
infrastructure/stacks/development-and-deployment-tools/delete_blue_green_environment.tf
infrastructure/stacks/development-and-deployment-tools/delete_ecr_images.tf
infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_from_tag.tf
infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_on_pr_merged.tf
infrastructure/stacks/development-and-deployment-tools/pipeline_stages.tf
infrastructure/stacks/development-and-deployment-tools/production_smoke_test.tf
infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf
infrastructure/stacks/development-and-deployment-tools/task_env_deploy_and_test.tf
infrastructure/stacks/development-and-deployment-tools/trigger_rollback.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1417>**
This PR bumps up the pipeline docker image versions.

DS-1417 Bump Up Pipeline Docker Image Versions

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk
build/automation/var/project.mk
infrastructure/stacks/shared-resources/cloudwatch-alarms.tf
infrastructure/stacks/shared-resources/cloudwatch-waf-alarms.tf
infrastructure/stacks/shared-resources/splunk.tf
infrastructure/stacks/shared-resources/variables.tf
infrastructure/stacks/shared-resources/waf.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-721>**
This PR begins blocking invalid requests using WAF. However, currently counted rules will continue to be counted to not block those false positive requests.

DS-721 Apply Web Application Firewall in Block Mode

---

Makefile
build/automation/lib/docker.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1447>**
This PR removes the use of the tools image in the pipeline.

DS-1447 Run Pipeline Without Tools Image

---

build/automation/var/project.mk
infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf
infrastructure/stacks/blue-green-link/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1420>**
This PR merges the monitoring and data CloudWatch dashboards so variable functionality doesn't have to be duplicated and update data is available on one dashboard.

DS-1420 Merge CloudWatch Dashboards

---

application/service_matcher/reporting.py
application/service_matcher/tests/test_reporting.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1139>**
This PR removes the UNMATCHED_SERVICE_TYPE from the application. The integration tests have already been removed.

DS-1139 Remove Unmatched Service Type Report

---

application/service_matcher/reporting.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_reporting.py
application/service_matcher/tests/test_service_matcher.py
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F007_Reporting.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1368>**
Remove all references to the UNEXPECTED_PHARMACY_PROFILING report.

DS-1368 Remove Unexpected Pharmacy Profiling Report

---

application/service_sync/data_processing/check_for_change.py
application/service_sync/data_processing/tests/test_check_for_change.py
application/service_sync/reporting.py
application/service_sync/tests/test_reporting.py
test/integration/features/F007_Reporting.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1369>**
This PR removes the INCORRECT_PALLIATIVE_STOCKHOLDER_TYPE report.

DS-1369 Remove Invalid Palliative Stockholder Service Report

---

application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1487>**
This PR adds an update request sent which is useful for seeing traffic pass through the system particularly in performance testing.

DS-1487 Add Update Request Sent Metric

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/functions/dos/get_data.py
test/integration/steps/functions/generator.py
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1469>**
This PR adds integration tests for DS-1316.

DS-1469 Add New Palliative Care Integration Tests

---

Makefile
README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1537>**
This PR removes old make targets which use to be used for performance testing in pipelines.

DS-1537 Remove Legacy Make Targets

---

README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1539>**
This PR removes legacy documentation and begins improving documentation.

DS-1539 Remove Legacy Documentation

---

application/service_sync/data_processing/check_for_change.py
application/service_sync/data_processing/tests/test_check_for_change.py
test/integration/features/F006_Opening_Times.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1013>**
This PR block blank opening times from causing standard opening times changes.

DS-1013 Blank Standard Opening Times No Update

---

test/integration/features/F006_Opening_Times.feature
test/integration/features/F007_Reporting.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1519>**
This PR updates the integration test suite for DS-1013.

DS-1519 Update Blank Opening Times Integration Tests

---

application/service_matcher/matching.py
application/service_matcher/reporting.py
application/service_matcher/review_matches.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_matching.py
application/service_matcher/tests/test_review_matches.py
application/service_matcher/tests/test_service_matcher.py
application/service_sync/reject_pending_changes/tests/test_pending_changes.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1367>**
This PR refactors the service matcher as well as adding a new log to the missing service type report if the main pharmacy doesn't exist and palliative care should be switched on.

DS-1367 New Missing Service Type

---

test/integration/features/F007_Reporting.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1520>**
This PR adds integration tests to check when the matching services are missing a palliative care service type.

DS-1520 Missing Service Type Integration Tests

---

test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1603>**
This PR removes an old broken test and removes an irrelevant dev tag.

DS-1603 Refactor Integration Tests - Remove Old Test and Irrelevant Tag

---

README.md
application/requirements-dev.txt
build/automation/var/profile/dev.mk
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-batch-jobs/integration-test.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/locals.tf
test/integration/README.md
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F003_DoS_Security.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F005_Support_Functions.feature
test/integration/features/F006_Opening_Times.feature
test/integration/features/F007_Reporting.feature
test/integration/steps/pytest.ini

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1399>**
This PR refactors the integration tests to use new tags. These new tags split the integration tests into multiple AWS CodeBuild jobs ensuring faster runs.

DS-1399 Refactor Integration Tests - Update Tag Groups

---

build/automation/var/profile/dev.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1619>**
This PR fixes the dev environment to use the correct database name to ensure CloudWatch graphs show the correct values.

DS-1619 Fix Development Environment Typo

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-batch-jobs/deploy-prerequisites.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/pipeline_stages.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1611>**
This PR reduces the deployment time in the task deploy and test CodeBuild batch. This further reduces the CodeBuild pipeline time to less than 20 mins on average.

DS-1611 Reduce Task Deploy and Test Deployment Time

---

infrastructure/stacks/shared-resources/data.tf
infrastructure/stacks/shared-resources/locals.tf

Please don't modify this description yet it will be populated once you create the pull request.

DS-1589 Update KMS Policy

---

application/common/dos.py
application/common/dos_db_connection.py
application/common/nhs.py
application/common/tests/test_utilities.py
application/common/utilities.py
application/ingest_change_event/change_event_validation.py
application/ingest_change_event/ingest_change_event.py
application/ingest_change_event/tests/test_ingest_change_event.py
application/service_sync/data_processing/check_for_change.py
application/service_sync/data_processing/comparison.py
application/service_sync/data_processing/service_histories.py
application/service_sync/reporting.py
application/service_sync/tests/test_reporting.py
build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1627>**
This PR trims the application to reduce the log size and count forwarded from the log group to Splunk.

DS-1627 Trim Application Logging

---

README.md
application/quality_checker/reporting.py
application/quality_checker/search_dos.py
application/quality_checker/tests/test_reporting.py
application/quality_checker/tests/test_search_dos.py
build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk
deployment/serverless.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-batch-jobs/integration-test.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/locals.tf
test/integration/features/F008_Quality_Checker.feature
test/integration/steps/functions/aws/aws_lambda.py
test/integration/steps/functions/aws/cloudwatch.py
test/integration/steps/functions/dos/translation.py
test/integration/steps/functions/generator.py
test/integration/steps/functions/utils.py
test/integration/steps/pytest.ini
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1658>**
This PR adds integration tests for the quality checker lambda to ensure all matching and reporting functionality is tested.

DS-1658 Quality Checker Integration Tests

---

infrastructure/stacks/shared-resources/waf.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1571>**
This PR sets the Web Application Firewall to allow large payloads which were previously blocked.

DS-1571 Fix Broken Web Application Firewall Rule

---

.github/workflows/configs/markdown-check-links.json
README.md
scripts/compare_di_to_dos_scripts/readme.md
test/integration/README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1678>**
This PR removes references to `tx-mfa` which has now been replaced with Granted `assume`

DS-1678 Remove References to tx-mfa

---

.github/workflows/code-quality.yml
Makefile
README.md
application/common/commissioned_service_type.py
application/requirements-dev.txt
application/service_sync/data_processing/formatting.py
application/service_sync/data_processing/tests/test_comparison.py
application/service_sync/tests/test_service_update_logger.py
build/automation/etc/githooks/scripts/python-code-pre-commit.sh
pyproject.toml
test/integration/steps/functions/dos/get_data.py
test/integration/steps/functions/generator.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1689>**
This PR bumps up the Ruff version to 1.5 and begins using Ruff format.

DS-1689 Bump Up Ruff Version and Implement Ruff Formatting

---

application/change_event_dlq_handler/change_event_dlq_handler.py
application/change_event_dlq_handler/tests/test_change_event_dlq_handler.py
application/common/utilities.py
application/dos_db_update_dlq_handler/dos_db_update_dlq_handler.py
application/ingest_change_event/ingest_change_event.py
application/quality_checker/quality_checker.py
application/quality_checker/reporting.py
application/service_matcher/reporting.py
application/service_matcher/service_matcher.py
application/service_matcher/tests/test_service_matcher.py
application/service_sync/reporting.py
application/service_sync/service_sync.py
application/service_sync/service_update_logger.py
infrastructure/stacks/after-lambda-deployment/splunk.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1641>**
This PR only sends WARNING, ERROR and CRITICAL logs to Splunk. DEBUG and INFO logs are no longer forwarded to Splunk.
Note: Metrics are sent through to Splunk as WARNING logs.

DS-1641 Only Send Relevant Logs and Metrics to Splunk

---

documentation/adr/012-Application-Metrics.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1709>**
This PR adds an architectural decision record (ADR) for generating CloudWatch Metrics.

DS-1709 Add Architectural Decision Record for Application Metrics

---

infrastructure/stacks/shared-resources/locals.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1724>**
This PR fixes the incorrect principals in the IAM policy for the KMS keys in the production account.

DS-1724 Fix KMS Principals Being Set Incorrectly

---

application/common/dos.py
application/common/tests/test_dos.py
application/service_matcher/matching.py
application/service_matcher/tests/test_matching.py
infrastructure/stacks/application/iam.tf
infrastructure/stacks/application/lambda.tf
infrastructure/stacks/application/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1687>**
This PR removes usage of the Pharmacy First Phase Once Parameter from the Application (Python code)

DS-1687 Remove Pharmacy First Parameter Usage

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
test/integration/features/F002_Invalid_Change_Events.feature
test/integration/features/F004_Error_Handling.feature
test/integration/features/F007_Reporting.feature
test/integration/features/F008_Quality_Checker.feature

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1721>**
This PR updates the task deploy and test pipeline to reduce duration. As well it removes duplicate and crazy tests.

DS-1721 Task Testing Changes and Integration Test Changes

---

test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1772>**
This PR fixes a couple broken sequence number tests when the change event is being deduplicated in a SQS queue. This should fix the development pipeline.

DS-1772 Fix Broken Sequence Number Tests

---

application/service_sync/data_processing/comparison.py
application/service_sync/data_processing/formatting.py
application/service_sync/data_processing/tests/test_formatting.py
test/integration/features/F001_Valid_Change_Events.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1723>**
This PR begins formatting the public phone number to remove any spaces within the phone number string. This includes leading, trailing spaces and in the middle.

DS-1723 Format Public Phone Number

---

test/smoke/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1787>**
This PR fixes the when a fake phone number is generated with a space. Instead this is removed by the application which breaks the assert the same update is applied to the database.

DS-1787 Fix Smoke Test Phone Updates

---

Makefile
infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1755>**
This PR updates the `trigger-dos-deployment-pipeline` make target to work with the new DoS pipeline on the new Jenkins.

DS-1755 Update DoS Environment Setup for New Jenkins

---

infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1806>**
This PR adds labels to the CPU utilisation and db connections database graphs to show the type of database it is within the Aurora Cluster

DS-1806 Add Database Labels to CloudWatch Dashboard

---

Makefile
README.md
pyproject.toml
pytest.ini
scripts/dynamodb_to_csv.py
scripts/performance_test_results/cloudwatch.py
scripts/performance_test_results/metrics.py
scripts/performance_test_results/performance_test_results.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1815>**
This PR adds a make target to collect performance test results after a performance test. These results can then be added to Confluence.

DS-1815 Performance Test Results Script

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk
build/automation/var/project.mk
infrastructure/stacks/application/data.tf
infrastructure/stacks/application/security_groups.tf
infrastructure/stacks/application/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-867>**
This PR updates the security group ingress rules to remove one of the security group rules and migrate to the new DoS Aurora security group.

DS-867 Update Security Group Ingress Rules for New Security Group

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/live.mk
build/automation/var/profile/perf.mk
build/automation/var/profile/perf2.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-932>**
This PR updates the database route 53 address to use the new ones associated with the upgrade to Aurora.

DS-932 Update Database Route 53 Addresses

---

build/automation/var/project.mk
infrastructure/stacks/shared-resources/parameter-store.tf
infrastructure/stacks/shared-resources/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1708>**
This PR removes the pharmacy first feature flag parameter store and associated variables.

DS-1708 Remove Pharmacy First Feature Flag Parameter Store

---

.github/workflows/codeql-analysis.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1925>**
Bumps [github/codeql-action](https://github.com/github/codeql-action) from 2 to 3.
- [Release notes](https://github.com/github/codeql-action/releases)
- [Changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/github/codeql-action/compare/v2...v3)

DS-1925 Upgrade CodeQL Version To 3

---

.github/workflows/check-pull-request-checklist.yml
.github/workflows/pull-request.yml
.github/workflows/update-pull-request-description.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1926>**
This PR updates multiple GitHub Actions versions and should stop the Dependabot PR description from being overwritten.

DS-1926 Updates GitHub Actions Versions and Configurations

---

.github/workflows/configs/vale/styles/Vocab/words/accept.txt
README.md
documentation/Onboarding.md
documentation/adr/001-High-level_design_and_tech_stack.md
documentation/adr/002-Reporting-approach.md
documentation/adr/010-Improve-Application-Performance.md
scripts/compare_di_to_dos_scripts/readme.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1934>**
This PR adds Vale improvements and updates documentation to hit less of the warnings.

DS-1934 Add Vale Fixes and Improve Documentation

---

infrastructure/stacks/development-and-deployment-tools/security_groups.tf
infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1957>**
This PR updates the CodeBuild Security Group to ensure remove any manually added rules and improve traceability.

DS-1957 Update MGMT Security Group Name

---

infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1958>**
This PR fixes the Schedule for the Setup of the DoS environment.

DS-1958 Fix DoS Environment Setup Schedule

---

scripts/performance_test_results/metrics.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1964>**
This PR improves the performance test results script by rounding the results of the metric outputs. As well as adding a % sign after the CPU Utilisation percentage.

DS-1964 Improve Performance Test Results Script

---

infrastructure/stacks/application/iam.tf
infrastructure/stacks/application/lambda.tf
infrastructure/stacks/application/security_groups.tf
test/integration/steps/functions/aws/aws_lambda.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1966>**
This PR improves lambda IAM permissions by restricting permissions to only what is necessary.

DS-1966 Improve Lambda IAM Permissions

---

Makefile
build/automation/lib/slack/codebuild-pipeline-pr-merge-failure.json
build/automation/lib/slack/codebuild-pipeline-pr-merge-success.json
infrastructure/stacks/development-and-deployment-tools/buildspecs/delete-nonprod-environment-on-pr-merged-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1972>**
This PR adds two new slack templates and updates the `slack-codebuild-notification` make target to correctly display the PR number instead of the branch information which isn't available when triggered by the PR being merged.

DS-1972 Fix Environment Removal Slack Message

---

infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-batch-jobs/build-arm-image.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-batch-jobs/remove-set-environment.yml
infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-buildspec.yml
infrastructure/stacks/development-and-deployment-tools/build_deploy_test_release.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1973>**
This PR is to remove the nonprod release environment after deployment and testing is complete. This environment is created on each push of a release branch before the branch is merged into main.

DS-1973 Remove Release Environment After Testing

---

build/automation/var/project.mk
infrastructure/stacks/application/lambda.tf
infrastructure/stacks/application/variables.tf
infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
infrastructure/stacks/blue-green-link/cloudwatch-events.tf
infrastructure/stacks/blue-green-link/data.tf
infrastructure/stacks/blue-green-link/variables.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1991>**
This PR adds an AWS EventBridge schedule to trigger the Quality Checker Lambda weekly.

DS-1991 Add Quality Checker Schedule

---

.editorconfig
.github/workflows/configs/vale/styles/Google/Will.yml
.github/workflows/configs/vale/styles/write-good/TooWordy.yml
documentation/disaster-recovery.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-1986>**
This PR adds an initial disaster recovery plan to begin to understand the disaster recovery landscape.

DS-1986 Add Disaster Recovery Plan

---

application/common/tests/test_dynamodb.py
application/common/tests/test_secretsmanager.py
application/conftest.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2154>**
This PR upgrades the dynamodb and secretsmanager mocking in the lambda unit tests to work with moto 5.0.0.

DS-2154 Upgrade Moto Mocking

---

infrastructure/stacks/application/lambda.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2170>**
This PR fixes an EventBridge Rule permission issue.

DS-2170 Fix Quality Checker EventBridge Rule Permission

---

.github/workflows/configs/vale/styles/config/vocabularies/words/accept.txt
.vale.ini
README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2261>**
Update Vale config to not fail in develop.

Remove Vale Violations

---

application/service_sync/data_processing/comparison.py
application/service_sync/data_processing/tests/test_comparison.py
application/service_sync/reporting.py
application/service_sync/tests/test_reporting.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2264>**
Upgrade to use latest AWS Lambda PowerTools Logging Standards by changing extra elements to instead be key word arguments.

DS-2264 Upgrade to use latest AWS Lambda PowerTools Logging Standards

---

infrastructure/stacks/development-and-deployment-tools/buildspecs/deploy-shared-resources-environment-buildspec.yml

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2275>**
Updates the `infrastructure/stacks/development-and-deployment-tools/buildspecs/deploy-shared-resources-environment-buildspec.yml` file to include showing the blue/green version variables.

DS-2275 Show Blue/Green Environment Variables in Shared Resources Deployment

---

infrastructure/stacks/shared-resources/dynamodb.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2362>**
Adds a tag on the DynamoDB table to indicate we won't be using Texas's backup solution. We covered by PiTR (Point in Time Recovery)

Add Texas backup tag to dynamoDB

---

build/automation/init.mk

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2941>**

DS-2941 Fix Make Targets

---

infrastructure/stacks/shared-resources/api-gateway-responses.tf
infrastructure/stacks/shared-resources/api-gateway.tf
test/integration/features/F001_Valid_Change_Events.feature
test/integration/features/F003_DoS_Security.feature
test/integration/features/F004_Error_Handling.feature
test/integration/steps/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-2829>**

DS-2829 Add missing HTTP security headers

---

test/integration/steps/functions/aws/aws_lambda.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-3685>**

Increasing Read timeout for lambda in IT tests

---

test/smoke/functions/base_change_event.json
test/smoke/functions/constants.py
test/smoke/test_steps.py

**<https://nhsd-jira.digital.nhs.uk/browse/DS-3746>**
Change Smoke test service as the current one has been removed
- Bug fix (non-breaking change which fixes an issue) (Test bug)

DS-3746 Change test smoke test service to one that exists

---

infrastructure/stacks/development-and-deployment-tools/development_pipeline.tf
infrastructure/stacks/development-and-deployment-tools/github.tf

**<https://nhsd-jira.digital.nhs.uk/browse/DS-3900>**
This PR revert changes from the last PR #1069
- Bug fix (reverting changes from last PR #1069)

DS-3900 Revert 1069 fixing dev pipeline trigger

---

README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-3900>**
This PR is to test the development pipeline trigger after manual release pushed from AWS CP post the org transfer
- Bug fix (Development pipeline trigger fix)

DS-3900 Pushing change to test the dev pipeline trigger fix

---

README.md

**<https://nhsd-jira.digital.nhs.uk/browse/DS-4012>**

DS-4012 Trigger Dev pipeline
