- infrastructure/stacks/lambda-iam-roles/main.tf
- https://nhsd-jira.digital.nhs.uk/browse/DI-277
Missing sqs:GetQueueAttributes permissions which is required as per documentation https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html
> Add more missing permissions in attempt to get pipeline going

- infrastructure/stacks/lambda-iam-roles/main.tf
- https://nhsd-jira.digital.nhs.uk/browse/DI-278
Add missing permission for lambda to query the dynamodb index
> Add missing permission

- application/event_processor/changes.py
- application/event_processor/tests/test_changes.py
- build/automation/var/profile/dev.mk
- build/automation/var/profile/task.mk
- deployment/serverless.yml
- https://nhsd-jira.digital.nhs.uk/browse/DI-264
This make sure if the postcode is invalid then the address is removed from the change request
> DI-264 Invalid Postcode does not prevent Address Updates

- application/event_processor/changes.py
- https://nhsd-jira.digital.nhs.uk/browse/DI-303
Changed a log.warn() to log.warning() as the former wasn't adding required metadata to log.
Changed a log.warn() to log.warning() as the former wasn't adding required metadata to log.
> Changed log warn to log warning

- application/common/encryption.py
- application/common/encryption_helper.py
- application/common/tests/test_encryption.py
- application/event_processor/event_processor.py
- application/event_processor/tests/test_event_processor.py
- infrastructure/stacks/development-pipeline/policies.tf
-
Did some refactoring to the encryption stuff so that they key is global so that it only got once per container creation
- Refactor
> Rework the encryption store key as global for speed

- Makefile
- build/automation/var/project.mk
- infrastructure/stacks/development-pipeline/integration-tests-buildspec.yml
- test/integration/steps/pytest.ini
- test/integration/steps/utilities/log_stream.py
This PR allows for the integration tests to have the number of parallel tests count set by a variable. By default this is set to auto. Also it increases the delay for some tests to reduce failures. As well removes many pytest tag warnings.
> Allow setting number of parallel tests

- application/event_processor/changes.py
- application/event_processor/event_processor.py
- application/event_processor/reporting.py
- application/event_processor/tests/test_event_processor.py
- application/event_processor/tests/test_reporting.py
- https://nhsd-jira.digital.nhs.uk/browse/DI-311
Added report logging to splunk for invalid opening times.
- Initial check of invalid opening times for NHS Entity object for case of logging (subsequent checks used to skip adding to change req)
- Unit tests to run on scenario of invalid opening times entered.
> DI-311 Report logging in event processor for invalid open times

- test/integration/features/parent_features.feature
- test/integration/steps/test_parent_steps.py
https://nhsd-jira.digital.nhs.uk/browse/DI-314
This change is the addition of a single assertion step to check the error_msg field contents in the eventbridge dlq logs. The phrasing uses a variable, so it could feasibly check for an error_msg field in any log in future test cases.
Worth noting that this only tests the second DLQ. The first does not have the ability to force an error, so that is not covered in the integration test.
- New integration test step and feature
> DI-314 Added new scenario to check additional DLQ logs

- application/test_db_checker_handler/test_db_checker_handler.py
- application/test_db_checker_handler/tests/test_test_db_checker_handler.py
- infrastructure/stacks/development-pipeline/integration-tests-buildspec.yml
- test/integration/steps/utilities/events.py
This PR removes a use case that can't be replicated where the DoS Address ends in a `$` and fixes a test report error
> Fix integration test dos address error

- Makefile
- application/dos_api_gateway/dos_api_gateway.py
- application/event_sender/change_request_logger.py
- application/event_sender/event_sender.py
- application/event_sender/tests/test_change_request_logger.py
- application/event_sender/tests/test_event_sender.py
- infrastructure/stacks/cloudwatch-dashboard/main.tf
- infrastructure/stacks/dos-api-gateway-mock/dos-api-gateway-mock-lambda.tf
- infrastructure/stacks/dos-api-gateway-mock/variables.tf
- infrastructure/stacks/lambda-iam-roles/main.tf
- https://nhsd-jira.digital.nhs.uk/browse/DI-331
This PR is to add tools to chaos test the DI application including turning off the DoS API Gateway Mock.
- Improved logging around health checks in the event sender
- Add dynamodb IAM permissions to event sender
- Fixed a bug if the DoS API Gateway doesn't exist (service unavailable)
> DI-331 Chaos Test Circuit Breaker

- application/common/opening_times.py
- application/common/tests/test_dos.py
- application/event_processor/changes.py
- application/event_processor/tests/test_changes.py
-https://nhsd-jira.digital.nhs.uk/browse/DI-346
Not creating an address change request (CR) when the address is same but not the postcode.
- Removed update_changes_with_address method in changes.py 
- Rename update_changes_with_postcode to update_changes_with_address_and_postcode 
- Combined both the fuctionality in one method and updated the unit tests.
> DI-346 Create Change Request(CR) when address lines are same but not the postcode

- application/common/tests/conftest.py
- application/event_processor/event_processor.py
This PR is to fix where objects are logged rather than the data the class holds.
As well I have fixed a deprecation warning in the unit tests
> Improve lambda logging

- test/integration/features/F006_Opening_times.feature
- test/integration/steps/test_parent_steps.py
- test/integration/steps/utilities/utils.py
https://nhsd-jira.digital.nhs.uk/browse/DI-375
-
Dos API currently has a limit 100 on the number of characters for the Correlation Id when invoked. Modifying the Correlation Id character limit in the Utils file on Test suite will facilitate replaying of Changed Events with additional characters on the correlation Id for specific scenarios.
Affected scenarios: F006S008 & F006S009
Added new scenario F006S010
Modified Correlation id to accomodate change event replays.
> DI-375 Modify correlation id character length limit

- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/steps/test_parent_steps.py
-https://nhsd-jira.digital.nhs.uk/browse/DI-390
A change was implemented that added an error message when a generic bank holiday time is set. There is only one in the DB so the ODS Code has been hard coded.
Very simple change nothing particularly of note.
- Integration test
> DI-390 Added new integration test for generic bank holidays

- test/integration/features/F001_Valid_Change_Events.feature
- test/integration/features/F004_Error_Handling.feature
- test/integration/features/F006_Opening_times.feature
- test/integration/steps/utilities/events.py
- test/integration/steps/utilities/utils.py
https://nhsd-jira.digital.nhs.uk/browse/DI-405
The "get_single_service_odscode" function only works on pharmacies and should not require an input parameter as the function invokes a lambda function which has now been modified to make use of a single "type" parameter to execute the payload query.
- Refactor the function in Test suite to retrieve single service pharmacies
> DI-405 Fix bug on retrieving pharmacy single service function

- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/steps/test_parent_steps.py
- test/integration/steps/utilities/aws.py
- https://nhsd-jira.digital.nhs.uk/browse/DI-406
This ticket adds a few new things.
There is a new generic log check step that will enable the user to specify a log group, a field, and a message to be verified. This will allow multiple tests to be moved across to this format, limiting the amount of test steps that are required.
There is also a new step that checks the opposite, that a certain log entry is not present, however this has required multiple requests to be made.
The new function in aws.py verifies that no logs are returned, and returns True, if nothing was found.
The new step runs the following:
An initial request to check logs for the correlation ID to find the function request ID.
A second request to ensure that the end step for the request ID has been found. This ensures …
> DI-406 Edge cases for dentist ods

- Makefile
- infrastructure/stacks/deployment-pipelines/demo_codebuild.tf
- infrastructure/stacks/deployment-pipelines/live_codebuild.tf
- infrastructure/stacks/development-pipeline/build-image-buildspec.yml
- infrastructure/stacks/development-pipeline/build_environment.tf
- infrastructure/stacks/development-pipeline/build_image_codebuild.tf
- infrastructure/stacks/development-pipeline/codepipeline.tf
- infrastructure/stacks/development-pipeline/data.tf
- infrastructure/stacks/development-pipeline/delete-ecr-images-buildspec.yml
- infrastructure/stacks/development-pipeline/delete-task-environment-from-tag-buildspec.yml
- infrastructure/stacks/development-pipeline/delete-task-environment-on-pr-merged-buildspec.yml
- infrastructure/stacks/development-pipeline/delete_ecr_images.tf
- infrastructure/stacks/development-pipeline/delete_task_environment_from_tag.tf
- infrastructure/stacks/development-pipeline/delete_task_environment_on_pr_merged.tf
- https://nhsd-jira.digital.nhs.uk/browse/DI-185
This PR is create an AWS codebuild stage to delete ECR images. The images that will be deleted are ones that are untagged and ones that are tagged for the task environment and older than a month. To find the image is a task environment image I check for the year in the repository such as 2022 or 2021.  Also images have to be older than a month as when an image is deleted and it is still used by the cloudformation stack it complains on update. So to fix this only old images will be removed as we don't tend to hold on to environments for that long. If this does occur destroying and rebuilding the environment will clear the issue
A good example is build 28 of the codebuild project.
- This has been tested on the event-sender repository
- This …
> DI-185 Create ECR clean up process

- application/common/tests/test_dos.py
- application/event_replay/event_replay.py
- application/event_replay/tests/test_event_replay.py
- https://nhsd-jira.digital.nhs.uk/browse/DI-358
As per the current architecture dentist changed events will be stored as normal like pharmacy changed events for DLQ and replay purpose
- Added missing org_type to event replay logs
> DI-358 Add org type info  to event replay logs

- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/features/F004_Error_Handling.feature
- test/integration/steps/test_parent_steps.py
- test/integration/steps/utilities/utils.py
- https://nhsd-jira.digital.nhs.uk/browse/DI-409
This ticket refactors a lot of the log checks within the test suite. They now use as few steps as possible to achieve this. 
There have, as a result, been several deleted steps.
All evidence of changed steps running succesfully is included in the ticket DI-409.
F002S001 Then to And
F002S001 - 
the unmatched service exception is reported to cloudwatch
to 
the Event "processor" shows field "message" with message "No matching DOS services"
F002S001 -
no matched services were found
to
the Event "processor" shows field "message" with message "Found 0 services in DB"
F002S001 - 
the Changed Event is not processed any further
to
the Event "processor" does not show "message" with message "Received change request"
F002S002 - 
the hidden or closed …
> DI-409 Refactoring of log check tests

- Makefile
- build/automation/var/profile/perf.mk
- build/automation/var/profile/tools.mk
- build/automation/var/project.mk
- https://nhsd-jira.digital.nhs.uk/browse/DI-434
The performance environment is a shared environment and we need to therefore arrange times when we apply load. As such we should set the performance test to run against Mock DOS by default and use this for our overnight performance tests and then update config when we have arranged a full end to end test to point to the real one.
- Add mock into the deploy make for perf env and update env vars to point the event sender to the mock by default
> DI-434 Change perf to use mock api

- application/event_processor/event_processor.py
- application/event_sender/event_sender.py
This is a log so that new CRs can be monitored.
This has passed unit tests when run
> DI-428 Add logging for change requests created

- .github/workflows/code-quality.yml
- https://nhsd-jira.digital.nhs.uk/browse/DI-451
> DI-451 Update Sonarcloud to include Serverless Framework and Terraform

- Makefile
- infrastructure/stacks/perf-test-tools/codebuild.tf
This PR fixes the AWS Codebuild stage that runs the performance tests using the incorrect environment. So now it is pointed to `perf` rather than `tools`
> Fix Performance Test Runner

- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/steps/test_steps.py
This is an update for the opening times changes made in DI-472.
There are 2 new tests, 1 for dentists, 1 for pharmacies.
The tests consist of a log check for the new removed value.
It is not possible to add tests to verify the event sender has removed these values, since the event sender may not be populated with any information if there are no other changes made, and the only change was ignored.
Tests have been run on the DI-472 environment.
The all_nhs field is always a list object containing strings, so the test verifying all_nhs.0 will always find the value, as there are never any sub arrays to be checked. The Log Insights query automatically names the field all_nhs.0.
> DI-477 Integration tests for past opening times

- infrastructure/stacks/release-pipeline/data.tf
This PR is to add the mock lambdas back into the release pipeline which is now needed by the performance environment by default
> Add DoS API Gateway mock lambdas back into release pipeline

- test/integration/features/F006_Opening_times.feature
- test/integration/steps/test_steps.py
- test/integration/steps/utilities/change_event_builder.py
Please don't modify this description yet it will be populated once you create the pull request.
> DI-547 Specified opening time bug fix test

- build/automation/var/project.mk
This PR is to fix a bug in DI-518 where it tries to rebuild the security group but the deletion fails. So putting back the old security group name it doesn't have to rebuild the security group
> DI-518 Fix deleting security group

- Makefile
- test/integration/features/F001_Valid_Change_Events.feature
- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/steps/test_steps.py
- test/integration/steps/utilities/utils.py
- DI-560. This is testing changes made in the DI-519 epic
Why do these tests need to exist?/When should the test be run?
These tests exists to validate specific changes in the newly implemented servicehistories table, as well as to ensure that no changes have been made to that table recently.
> DI-560 Service history checks for integration

- Makefile
- test/integration/features/F006_Opening_times.feature
- test/integration/steps/test_steps.py
- test/integration/steps/utilities/utils.py
- DI-558 - Based off the DI-519 epic
Why do these tests need to exist?/When should the test be run?
These tests verify that the service history is updated for specified opening times changes.
> DI-558 Service history specified dates tests

- infrastructure/stacks/before-lambda-deployment/data.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DI-574>**
This PR is to merge in the hotfix for release 2.2 to allow cloudwatch alarms to access the KMS keys. This fixes the bug where cloudwatch alarms aren't being displayed in slack due to the alarm not being able to access the KMS Key
> DI-574 Allow Cloudwatch Alarms to read KMS Keys (Release 2.2) 

- test/integration/steps/test_steps.py
This PR is to remove a check and replace with a sleep where it checks the service has been updated. This is more reliable as it gives the change event chance to apply to the database
> Increase Integration Test Reliability

- Makefile
- application/send_email/requirements.txt
- application/send_email/send_email.py
- application/send_email/tests/test_send_email.py
- infrastructure/stacks/after-lambda-deployment/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DI-583>**
This PR adds a cloudwatch alarm to alarm when an email to fail sends
> DI-583 Email Monitoring Alarm

- Makefile
**<https://nhsd-jira.digital.nhs.uk/browse/DI-600>**
This bumps up the DoS version used in the Regressiondi environment so that DI can use the new database roles
> DI-600 Increase DoS Version in Regressiondi Environment

- deployment/serverless.yml
**<https://nhsd-jira.digital.nhs.uk/browse/DI-580>**
This PR is to disable rollback so that update can be rolled back using DI's rollback method or deploying an update over the top of the failed update. When a deployment fails the resource with causes the error won't deploy. This means that the previous deployed version continues to work.
After Green/Blue deployments this will only be useful in nonprod
> DI-580 Disable Serverless Framework Rollback

- Makefile
- deployment/serverless.yml
- infrastructure/stacks/before-lambda-deployment/outputs.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DI-576>**
This PR turns on standard s3 encryption for the deployment bucket but also KMS key encryption for the objects within the bucket.
> DI-576 Deployment bucket objects encryption

- .github/workflows/pull-request.yml
This PR changes the pull-request.yml workflow to not run when Dependabot opens a PR or on a release
> Refactor Pull Request Workflow to Stop False Positives

- application/change_event_dlq_handler/change_event_dlq_handler.py
- application/change_event_dlq_handler/tests/test_change_event_dlq_handler.py
- application/common/middlewares.py
- application/common/tests/STANDARD_EVENT_WITH_STAFF.json
- application/common/tests/conftest.py
- application/common/tests/test_middlewares.py
- application/common/tests/test_utilities.py
- application/common/utilities.py
- application/dos_db_handler/requirements.txt
- application/event_replay/requirements.txt
- application/ingest_change_event/ingest_change_event.py
- application/ingest_change_event/tests/conftest.py
- application/ingest_change_event/tests/test_ingest_change_event.py
- application/slack_messenger/requirements.txt
**<https://nhsd-jira.digital.nhs.uk/browse/DI-47>**
Redacts the 'Staff' key from the Change Event after it has been recieved but before it is log or save to dynamoDB. This is done by defining a new decorator function, which is applied to lambda handler for the ingest change event and the change event dlq handler.
> DSUEC-47 Redact `Staff` key and value from change event

- infrastructure/stacks/blue-green-link/cloudwatch-alarms-lambda-error-rate.tf
- infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-79>**
This code changes the alarms to mostly not be deployed in nonprod and also alert when an alarming alarm reverts back to ok state.
> DSUEC-79 Alert when Alarms revert to OK state

- Makefile
- test/integration/features/F001_Valid_Change_Events.feature
- test/integration/features/F002_Invalid_Change_Events.feature
- test/integration/steps/test_steps.py
- test/integration/steps/utilities/generator.py
**<https://nhsd-jira.digital.nhs.uk/browse/DI-70>**
Two new steps in tests to verify staff field redaction. A new step was added instead of using generic functionality because the error message does not contain a correlation id.
Staff field added to the generator for the CE.
- Test
> DI-70 Integration test for Staff field redaction

- application/common/nhs.py
- application/common/tests/test_nhs.py
**<https://nhsd-jira.digital.nhs.uk/browse/DSUEC-100>**
This PR allows the UecServices key of the change event to be different to what is expected. Within reason!. To ensure DI continues to function while the initial state is set to null in Profile Manager.
> DSUEC-100 Make Finding Palliative Care from Change Event More Robust

- application/common/dos.py
- application/common/dynamodb.py
- application/common/middlewares.py
- application/common/nhs.py
- application/common/opening_times.py
- application/common/tests/conftest.py
- application/common/tests/test_dynamodb.py
- application/common/tests/test_opening_times.py
- application/common/tests/test_report_logging.py
- application/common/utilities.py
- application/requirements-dev.txt
- application/service_matcher/service_matcher.py
- application/service_sync/changes_to_dos.py
- application/service_sync/compare_data.py
- application/service_sync/dos_data.py
- application/service_sync/format.py
- application/service_sync/pending_changes.py
- application/service_sync/service_histories.py
- application/service_sync/service_update_logging.py
- pyproject.toml
**<https://nhsd-jira.digital.nhs.uk/browse/DS-845>**
This PR adds Ruff refactoring to more service sync files. As well as removing GitHub maintainability warnings.
> DS-845 Remove GitHub Warnings and More Ruff Refactoring

- build/automation/var/profile/live.mk
Hotfix release to fix issue with the Serverless Framework deployment now requiring dos-db-handler lambda variables to be defined even when it isn't being deployed. See here for more details **<https://nhsd-jira.digital.nhs.uk/browse/DS-1183>**
> Release/16.1 - Hotfix

- Makefile
- test/performance/load_test_locustfile.py
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1198>**
This PR bumps up the load test load to be closer to NHS UK's max load. This sets the load test to 5 requests per second similar to NHS UK's traffic.
> DS-1198 Bump Up Load Test Event Load

- build/automation/var/profile/live.mk
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1183>**
Hotfix release to fix issue with the Serverless Framework deployment now requiring dos-db-handler lambda variables to be defined even when it isn't being deployed. See here for more details https://nhsd-jira.digital.nhs.uk/browse/DS-1183
> DS-1183 Fix live db-dos-handler variable not being defined (Hotfix 16.1)

- infrastructure/stacks/blue-green-link/cloudwatch-dashboards.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1332>**
This PR adds CloudWatch Dashboard variables to allow dashboard version switching between the current and rollback versions.
> DS-1332 Add Cloudwatch Dashboard Variables

- infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1372>**
This PR reduces the CloudWatch Alarm thresholds to match the SLA due to DI's now improved performance.
> DS-1372 Reduce CloudWatch Alarm Thresholds

- infrastructure/stacks/development-and-deployment-tools/pipeline_stages.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1435>**
This PR is to increase CodeBuild timeouts to ensure the pipelines don't timeout in the build stage.
> DS-1435 Increase Pipeline Build Timeouts

- infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1396>**
This PR removes unused CloudWatch Alarms which are no longer useful. As well alarm configurations are changed to reduce number of alerts.
> DS-1396 Remove Unused Alarms and Improve Alarm Triggers

- Makefile
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1490>**
This PR increases the rate of the stress test to not finish within 30 mins
> DS-1490 Increase Stress Test Rate

- test/smoke/functions/change_event.py
- test/smoke/functions/service.py
- test/smoke/functions/smoke_test_context.py
- test/smoke/test_steps.py
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1655>**
This PR allows the smoke test to work when the initial state of a service has a blank opening time.
> DS-156 Fix Blank Opening Times in Production Smoke Test

- .github/workflows/SECURITY.md
- .github/workflows/configs/markdown-check-links.json
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1602>**
This PR adds the default NHS Security Policy from the template repository which can be found here -> https://github.com/nhs-england-tools/repository-template/blob/main/.github/SECURITY.md
> DS-1602 Add Repository Security Policy

- infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1767>**
This PR updates the Quality Checker Schedule Failed Invocation alert to use the correct metric from `Invocation` to `FailedInvocation`
> DS-1767 Fix Failed Quality Checker Invocation Alert

- infrastructure/stacks/blue-green-link/cloudwatch-alarms-lambda-error-rate.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1792>**
This PR removes the Lambda Error Rate Alarms alerting that they are OK when there is no data which is a false positive instead it should now change to missing when there is no data. As such it changes state to `INSUFFICIENT_DATA`.
> DS-1792 Remove False Negatives from Lambda Error Rate Alarms

- infrastructure/modules/s3/main.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1633>**
This PR upgrade the version of the S3 used to store emails and logs of s3 usage. From `3.4.0` to `3.15.1`
> DS-1633 Upgrade Terraform S3 Module Version

- infrastructure/stacks/blue-green-link/cloudwatch-alarms.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1909>**
This PR modifies the alarms to not deploy into Task environments and fixes where the alarms are incorrectly not deployed into the release/cicd-test environments.
> DS-1909 Modify Alarms To Not Deploy Into Task Environments

- infrastructure/stacks/development-and-deployment-tools/build_cicd_blue_green_deployment_artefact.tf
- infrastructure/stacks/development-and-deployment-tools/build_cicd_shared_resources_artefact.tf
- infrastructure/stacks/development-and-deployment-tools/build_deploy_test_release.tf
- infrastructure/stacks/development-and-deployment-tools/build_tools_image.tf
- infrastructure/stacks/development-and-deployment-tools/cicd_blue_green_rollback.tf
- infrastructure/stacks/development-and-deployment-tools/delete_blue_green_environment.tf
- infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_from_tag.tf
- infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_on_pr_merged.tf
- infrastructure/stacks/development-and-deployment-tools/pipeline_stages.tf
- infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf
- infrastructure/stacks/development-and-deployment-tools/task_env_deploy_and_test.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1977>**
This PR updates the CodeBuild jobs to use the local buildspec file rather than a stored buildspec. This allows changes to be made to a branch rather than the change made for all branches
> DS-1977 Update CodeBuild To Use Local BuildSpecs

- test/smoke/test_steps.py
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1984>**
This PR fixes a bug with the Smoke Test which the specified opening times picks a date between now and the end of the year. As the year get closer to ending such as December less dates can be picked without picking a duplicate. So I've set the function to use `date_this_decade` which reduces the chance of the same date being picked twice.
> DS-1984 Fix Specified Opening Times Smoke Test Bug

- infrastructure/stacks/development-and-deployment-tools/build_deploy_test_release.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-1987>**
This PR fixes the `build-deploy-test-release` CodeBuild job using the incorrect path to the buildspec.
> DS-1987 Fix Missing Release Deploy and Test BuildSpec

- build/automation/var/profile/pen.mk
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2244>**
This change adds a penetration test profile call pen.mk. This profile is based of the dev.mk profile but enables the WAF.
> DS-2244 Add Penetration Test Make Profile

- infrastructure/stacks/development-and-deployment-tools/buildspecs/build-arm-image-from-webhook-buildspec.yml
- infrastructure/stacks/development-and-deployment-tools/buildspecs/build-arm-image-in-pipeline-buildspec.yml
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2408>**
This PR adds a temp fix to the missed build image codebuild jobs used by DI's pipelines. A 20 second sleep has been put in place to give time for the aws ecr security image scan to be ready, before it's checked.
> DS-2408 Add image build security scan fix to missed pipelines

- infrastructure/stacks/development-and-deployment-tools/buildspecs/build-arm-image-in-pipeline-buildspec.yml
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2622>**
Removes last ECR vulnerability scan check from the development pipeline, missed from previous two DS-2622 branches. The last one only removed it from webhook based buildspec.
Reason from removal can be found in the ticket. 
> DS-2622 Remove last missed ECR vulnerability scan check

- infrastructure/stacks/application/security_groups.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2834>**
Changed rule for port 5432 to only point to the dos-integration security group rather than any IP address.
- Bug fix (PEN test change)
> DS-2834 Restricted endpoint to security group

- build/automation/var/profile/demo.mk
- build/automation/var/profile/dev.mk
- build/automation/var/profile/live.mk
- build/automation/var/profile/pen.mk
- build/automation/var/profile/perf.mk
- build/automation/var/profile/perf2.mk
- build/automation/var/project.mk
- infrastructure/stacks/shared-resources/dynamodb.tf
- infrastructure/stacks/shared-resources/variables.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2843>**
This PR change enables the delete protection on change event DB in prod environment. This delete protection not enabled on any other env as we will require to tear the lower envs down after the development/testing purpose is fulfilled and tested in these lower env and hence it's enabled for prod env only to avoid accidental deletion of DB
- Security enhancement for dynamodb table in prod env
> DS-2843 Enable dynamodb delete protection for live profile

- build/automation/var/project.mk
- infrastructure/stacks/shared-resources/cloudwatch-waf-alarms.tf
- infrastructure/stacks/shared-resources/variables.tf
- infrastructure/stacks/shared-resources/waf.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-2844>**
This PR creates a custom WAF rule to identify the SQL injection attacks in change event request.
- Security enhancements(Prevention of SQL injections)
> DS-2844 Missing rule config for WAF SQLi rule

- README.md
- infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/build-deploy-test-release-buildspec.yml
- infrastructure/stacks/development-and-deployment-tools/batch-buildspecs/task-env-deploy-and-test-buildspec.yml
- infrastructure/stacks/development-and-deployment-tools/build_cicd_blue_green_deployment_artefact.tf
- infrastructure/stacks/development-and-deployment-tools/build_cicd_shared_resources_artefact.tf
- infrastructure/stacks/development-and-deployment-tools/build_deploy_test_release.tf
- infrastructure/stacks/development-and-deployment-tools/build_tools_image.tf
- infrastructure/stacks/development-and-deployment-tools/cicd_blue_green_rollback.tf
- infrastructure/stacks/development-and-deployment-tools/delete_blue_green_environment.tf
- infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_from_tag.tf
- infrastructure/stacks/development-and-deployment-tools/delete_nonprod_environment_on_pr_merged.tf
- infrastructure/stacks/development-and-deployment-tools/pipeline_stages.tf
- infrastructure/stacks/development-and-deployment-tools/setup_dos_environment.tf
- infrastructure/stacks/development-and-deployment-tools/task_env_deploy_and_test.tf
**<https://nhsd-jira.digital.nhs.uk/browse/DS-3786>**
Fixing issue of breaking test cases in new tester docker image
- Bug fix (CI/CD pipeline related change)
> DS-3786 Fixing breaking tester image
